### ISSUE TITLE
「山形市旅篭町二丁目3番25号」が解析できない

### ISSUE THREAD

**Issue by t-sagara** [digital-go-jp/abr-geocoder#1]
都道府県名の省略には対応しているようですが、都道府県名と市区町村名が同じ場合（青森県青森市, 山形県山形市など）に期待した解析結果にならないようです。
```
echo '山形市旅篭町二丁目3番25号' | abr-geocoder normalize - -f json
[
  {
    "pref": "山形県",
    "city": "",
    "town": "",
    "other": "市旅篭町二丁目3番25号",
    "lat": null,
    "lon": null,
    "level": 1
  }
]
```

**Comment by koswatana** [comment]
都道府県名がある場合
```
# echo '山形県山形市旅篭町二丁目3番25号' | abr-geocoder normalize - -f ndjson|jq .
{
  "pref": "山形県",
  "city": "山形市",
  "lg_code": "062014",
  "town": "旅篭町二丁目",
  "town_id": "0247002",
  "other": "",
  "lat": 38.255246956,
  "lon": 140.340220244,
  "level": 8,
  "addr1": "25",
  "blk": "3",
  "blk_id": "003",
  "addr1_id": "025",
  "addr2": "",
  "addr2_id": ""
}
```

**Comment by koswatana** [comment]
同様のケース
https://github.com/digital-go-jp/abr-geocoder/issues/15#issuecomment-1599261571

**Comment by maskatsum** [comment]
これ、期待する結果としては 「山形県」を自動で補則した検索結果になることだと思います。
コード中にそれを行うようなとことを見ましたので、そこが正しく機能していない可能性が高いです。
次の作業日に、この問題のデバッグを行います。

**Comment by koswatana** [comment]
ここの処理かな
https://github.com/digital-go-jp/abr-geocoder/blob/main/src/engine/normalize.ts#L316

**Comment by maskatsum** [comment]
現在、コードを全面的にリファクタリングを行っています。
その過程の中で、 `山形市旅篭町二丁目3番25号` に対する住所の正規化は期待する値に変換することができました。

オリジナルコードのどこに問題があったかは不明ですが、ロジックの最適化を行っているので、その中で（いまのところ）うまく機能しているようです。

*入力値*
```
東京都千代田区紀尾井町1-3　東京ガーデンテラス紀尾井町 19階、20階
東京都千代田区紀尾井町1
山形市旅篭町二丁目3番25号
```

*出力値*
```
東京都千代田区紀尾井町1-3 東京ガーデンテラス紀尾井町 19階、20階
東京都千代田区紀尾井町1
山形県山形市旅篭町二丁目3番25号
```

これで対応完了というわけではなく、あくまで途中経過の報告です。

**Comment by maskatsum** [comment]
ピンポイントでどこ、とは覚えていないですが、〇〇県〇〇市（〇〇が同じ）を検出するためのパターン生成の v1.0のコードにバグがあったことは覚えています。v1.1 で修正されました。

**Comment by maskatsum** [comment]
v1.1 がNPMリリースされました
https://www.npmjs.com/package/@digital-go-jp/abr-geocoder/v/1.1.0
