### ISSUE TITLE
コマンド名について

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#10]
`abr-geocoder` というコマンドは長いと思います。`abrg` など、省略されたコマンドの方が使いやすいと思いますがいかがでしょうか。

(`abr`は何の意味でしょうか）

**Comment by koswatana** [comment]
たしかにコマンドが長いのは同意です、ちなみにnpmjsに登録するパッケージ名はは`abr-geocoder`で、コマンド実行は`abrg`と分けられるものでしょうか？
abrはアドレス・ベース・レジストリ(Address Base Registry)の略です

**Comment by maskatsum** [comment]
https://github.com/digital-go-jp/abr-geocoder/blob/01bec959e1149629fccbf1fbe5d1360fcd3184c8/package.json#L20

> npmjsに登録するパッケージ名ははabr-geocoderで、コマンド実行はabrgと分けられるものでしょうか？

問題ありませんよ。package.json のここの部分を変更すれば良いだけです

**Comment by koswatana** [comment]
なるほど
あとは個人的にジオコーディングするサブコマンドが`normalize`なのが気になっています

**Comment by maskatsum** [comment]
そうですね、`normalize`のサブコマンドは省略したいですねー。
個人的にはデフォルトを json にしたいというのもあります。

こうしたい。

```
echo "(住所)" | abgr - | jq .
```

**Comment by maskatsum** [comment]
コマンドって、スクリプトファイルの中だと、ほぼパイプリングして使います。なので、`table` 出力は、ちょっと使いにくいなぁと思っています（まぁ単純にoutputを指定すればいいだけですけど）

**Comment by koswatana** [comment]
- コマンド名を`abrg`に変更
https://github.com/digital-go-jp/abr-geocoder/blob/01bec959e1149629fccbf1fbe5d1360fcd3184c8/package.json#L20
- ndjsonをデフォルト出力にする

**Comment by maskatsum** [comment]
PR #21 で完了
