### ISSUE TITLE
cityレベルでマッチしたがlg_codeが出力されないケースがある

### ISSUE THREAD

**Issue by koswatana** [digital-go-jp/abr-geocoder#106]
- version
```
root@1d508ffdfb5a:/workspaces/abr-geocoder# git log --oneline -1
e6372f4 (HEAD -> develop, origin/develop) Merge pull request #104 from digital-go-jp/features/issue90-2
```

```
root@1d508ffdfb5a:/workspaces/abr-geocoder# npx ts-node ./src/cli/cli.ts -f csv ./test.csv result.csv
```

[test.csv](https://github.com/digital-go-jp/abr-geocoder/files/14236659/test.csv)
[result.csv](https://github.com/digital-go-jp/abr-geocoder/files/14236680/result.csv)
![image](https://github.com/digital-go-jp/abr-geocoder/assets/103909883/dcd0d953-12be-4d53-b7c1-d4f071f7dd3c)

大阪市中央区上町Ｃ‐３ | 大阪府大阪市中央区上町C-3 | 2 |   | 大阪府 | 大阪市 |   |   |   |   |   |   |   |   | 中央区上町C-3 |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
大阪市北区天神橋2丁目北2番6号 | 大阪府大阪市北区天神橋2丁目北2番6号 | 2 |   | 大阪府 | 大阪市 |   |   |   |   |   |   |   |   | 北区天神橋2丁目北2番6号 |   |  
大阪市鶴見区諸口5丁目浜6番12号 | 大阪府大阪市鶴見区諸口5丁目浜6番12号 | 2 |   | 大阪府 | 大阪市 |   |   |   |   |   |   |   |   | 鶴見区諸口5丁目浜6番12号 |   |  
大阪市中央区久太郎町４丁目渡辺6号 | 大阪府大阪市中央区久太郎町4丁目渡辺6号 | 2 |   | 大阪府 | 大阪市 |   |   |   |   |   |   |   |   | 中央区久太郎町4丁目渡辺6号 |   |  
大阪市天王寺区堀越町アベノ地下街8号 | 大阪府大阪市天王寺区堀越町アベノ地下街8号 | 2 |   | 大阪府 | 大阪市 |   |   |   |   |   |   |   |   | 天王寺区堀越町アベノ地下街8号 |   |  
京都市東山区本町22丁目500番地 | 京都府京都市東山区本町22丁目500番地 | 2 |   | 京都府 | 京都市 |   |   |   |   |   |   |   |   | 東山区本町22丁目500番地 |   |  
北海道勇払郡安平町字安平番外地 | 北海道勇払郡安平町字安平番外地 | 2 |   | 北海道 | 勇払郡安平町 |   |   |   |   |   |   |   |   | 字安平番外地 |   |  
龍ケ崎市3710番地 | 茨城県龍ケ崎市3710番地 | 2 |   | 茨城県 | 龍ケ崎市 |   |   |   |   |   |   |   |   | 3710番地 |   |  
龍ケ崎市寺後3710番地 | 茨城県龍ケ崎市寺後3710番地 | 2 |   | 茨城県 | 龍ケ崎市 |   |   |   |   |   |   |   |   | 寺後3710番地 |   |  
龍ヶ崎市寺後3626-1 | 茨城県龍ケ崎市寺後3626-1 | 2 |   | 茨城県 | 龍ケ崎市 |   |   |   |   |   |   |   |   | 寺後3626-1 |   |  
長野県諏訪郡下諏訪町4613番地8 | 長野県諏訪郡下諏訪町4613番地8 | 2 |   | 長野県 | 諏訪郡下諏訪町 |   |   |   |   |   |   |   |   | 4613番地8 |   |  
長野県上伊那郡南箕輪村4825-1 | 長野県上伊那郡南箕輪村4825-1 | 2 |   | 長野県 | 上伊那郡南箕輪村 |   |   |   |   |   |   |   |   | 4825-1 |   |  
長野県東筑摩郡生坂村5493-2 | 長野県東筑摩郡生坂村5493-2 | 2 |   | 長野県 | 東筑摩郡生坂村 |   |   |   |   |   |   |   |   | 5493-2 |   |  
長野県上伊那郡宮田村98番地 | 長野県上伊那郡宮田村98番地 | 2 |   | 長野県 | 上伊那郡宮田村 |   |   |   |   |   |   |   |   | 98番地 |   |  
神奈川県綾瀬市無番地 | 神奈川県綾瀬市無番地 | 2 |   | 神奈川県 | 綾瀬市 |   |   |   |   |   |   |   |   | 無番地 |   |  
東京都八丈島八丈町大賀郷2551番地2 | 東京都八丈島八丈町大賀郷2551番地2 | 1 |   | 東京都 |   |   |   |   |   |   |   |   |   | 八丈島八丈町大賀郷2551番地2 |   |  
北海道紋別郡湧別町南兵村１区 | 北海道紋別郡湧別町南兵村1区 | 2 |   | 北海道 | 紋別郡湧別町 |   |   |   |   |   |   |   |   | 南兵村1区 |   |  
札幌市白石区南郷通6丁目北2-1 | 札幌市白石区南郷通6丁目北2-1 | 0 |   |   |   |   |   |   |   |   |   |   |   | 札幌市白石区南郷通6丁目北2-1 |   |  
十日町市本町1丁目上1番地18 | 新潟県十日町市本町1丁目上1番地18 | 2 |   | 新潟県 | 十日町市 |   |   |   |   |   |   |   |   | 本町1丁目上1番地18 |   |  
新潟県十日町市本町６の一丁目３８１－１ | 新潟県十日町市本町6の一丁目381-1 | 2 |   | 新潟県 | 十日町市 |   |   |   |   |   |   |   |   | 本町6の一丁目381-1 |   |  
厚岸郡厚岸町太田５の通り２３番地１ | 北海道厚岸郡厚岸町太田5の通り23番地1 | 2 |   | 北海道 | 厚岸郡厚岸町 |   |   |   |   |   |   |   |   | 太田5の通り23番地1 |   |  
新潟市西区五十嵐2の町8050番地 | 新潟県新潟市西区五十嵐2の町8050番地 | 2 |   | 新潟県 | 新潟市 |   |   |   |   |   |   |   |   | 西区五十嵐2の町8050番地 |   |  
京都市上京区日暮通丸太町下がる4-802-3 | 京都府京都市上京区日暮通丸太町下がる4-802-3 | 2 |   | 京都府 | 京都市 |   |   |   |   |   |   |   |   | 上京区日暮通丸太町下がる4-802-3 |   |  
京都市上京区堀川下立売上る4－55 | 京都府京都市上京区堀川下立売上る4-55 | 2 |   | 京都府 | 京都市 |   |   |   |   |   |   |   |   | 上京区堀川下立売上る4-55 |   |  
京都市中京区柳馬場通夷川上ル五丁目２３２番地の１ | 京都府京都市中京区柳馬場通夷川上ル五丁目232番地の1 | 2 |   | 京都府 | 京都市 |   |   |   |   |   |   |   |   | 中京区柳馬場通夷川上ル五丁目232番地の1 |   |  
京都市中京区寺町通御池上る上本能寺前町488番地 | 京都府京都市中京区寺町通御池上る上本能寺前町488番地 | 2 |   | 京都府 | 京都市 |   |   |   |   |   |   |   |   | 中京区寺町通御池上る上本能寺前町488番地 |   |  
京都市上京区下立売通新町西入薮ノ内町 | 京都府京都市上京区下立売通新町西入薮ノ内町 | 2 |   | 京都府 | 京都市 |   |   |   |   |   |   |   |   | 上京区下立売通新町西入薮ノ内町 |   |  
京都市上京区室町通下長者町通下ル近衛町38番地 | 京都府京都市上京区室町通下長者町通下ル近衛町38番地 | 2 |   | 京都府 | 京都市 |   |   |   |   |   |   |   |   | 上京区室町通下長者町通下ル近衛町38番地 |   |  
京都府京都市下京区油小路通木津屋橋通り上ル油小路282 | 京都府京都市下京区油小路通木津屋橋通り上ル油小路282 | 2 |   | 京都府 | 京都市下京区 |   |   |   |   |   |   |   |   | 油小路通木津屋橋通り上ル油小路282 |   |  
長野市若松町1028 | 長野県長野市若松町1028 | 2 |   | 長野県 | 長野市 |   |   |   |   |   |   |   |   | 若松町1028 |   |  
長野市新諏訪町 ６９０－３ | 長野県長野市新諏訪町690-3 | 2 |   | 長野県 | 長野市 |   |   |   |   |   |   |   |   | 新諏訪町690-3 |   |  
大分市大石町1丁目3組 | 大分県大分市大石町1丁目3組 | 2 |   | 大分県 | 大分市 |   |   |   |   |   |   |   |   | 大石町1丁目3組 |   |  
大分県中津市二ノ丁本丸 | 大分県中津市二ノ丁本丸 | 2 |   | 大分県 | 中津市 |   |   |   |   |   |   |   |   | 二ノ丁本丸 |   |  
北海道雨竜郡秩父別町字秩父別２０８５番地（２条１丁目） | 北海道雨竜郡秩父別町字秩父別2085番地（2条1丁目） | 2 |   | 北海道 | 雨竜郡秩父別町 |   |   |   |   |   |   |   |   | 字秩父別2085番地（2条1丁目） |   |  
北海道雨竜郡秩父別町4 1 0 1 番地（２条２丁目） | 北海道雨竜郡秩父別町4101番地（2条2丁目） | 2 |   | 北海道 | 雨竜郡秩父別町 |   |   |   |   |   |   |   |   | 4101番地（2条2丁目） |   |  
北海道雨竜郡雨竜町字尾白利加88番地38 | 北海道雨竜郡雨竜町字尾白利加88番地38 | 2 |   | 北海道 | 雨竜郡雨竜町 |   |   |   |   |   |   |   |   | 字尾白利加88番地38 |   |  
雨竜郡雨竜町第8町内 | 北海道雨竜郡雨竜町第8町内 | 2 |   | 北海道 | 雨竜郡雨竜町 |   |   |   |   |   |   |   |   | 第8町内 |   |

**Comment by koswatana** [comment]
![image](https://github.com/digital-go-jp/abr-geocoder/assets/103909883/5e46c283-b8fe-4472-a2b2-b67ac2e58b48)

**Comment by koswatana** [comment]
大阪府大阪市までマッチしたときに`271004`を出力するべきか

**Comment by koswatana** [comment]
そもそも大阪府大阪市中央区がマッチしていない

**Comment by maskatsum** [comment]
これ、全部マッチレベルが 2以下、のときですね。

**Comment by koswatana** [comment]
都道府県を省略するしないで結果が変わる
```
# echo "大阪市北区中之島1丁目3番20号"|npx ts-node ./src/cli/cli.ts - --format normalize
input,output,matching_level
"大阪市北区中之島1丁目3番20号","大阪府大阪市北区中之島1丁目3番20号",2
# echo "大阪府大阪市北区中之島1丁目3番20号"|npx ts-
node ./src/cli/cli.ts - --format normalize
input,output,matching_level
"大阪府大阪市北区中之島1丁目3番20号","大阪府大阪市北区中之島一丁目3-20",8
```

**Comment by maskatsum** [comment]
今やると、都道府県がなくてもマッチしますね。

```
[
  {
    "query": {
      "input": "大阪市北区中之島1丁目3番20号"
    },
    "result": {
      "output": "大阪府大阪市北区中之島一丁目3-20",
      "score": 0.67,
      "other": null,
      "match_level": "residential_detail",
      "lg_code": "271276",
      "pref": "大阪府",
      "county": null,
      "city": "大阪市",
      "ward": "北区",
      "machiaza_id": "0050001",
      "oaza_cho": "中之島",
      "chome": "一丁目",
      "koaza": null,
      "block": "3",
      "block_id": "003",
      "rsdt_num": 20,
      "rsdt_id": "020",
      "rsdt_num2": null,
      "rsdt2_id": null,
      "rsdt_addr_flg": 1,
      "prc_num1": null,
      "prc_num2": null,
      "prc_num3": null,
      "prc_id": null,
      "lat": 34.693870178,
      "lon": 135.50127668700003,
      "coordinate_level": "residential_detail"
    },
    "debug": {
      "pref_key": 5859296,
      "city_key": 3668593122,
      "town_key": 3513745081,
      "rsdtblk_key": 2248176261,
      "rsdtdsp_key": 47633577
    }
  }
]
```

**Comment by maskatsum** [comment]
開発中のv2

| input                       | score | output                          | other               | match_level        | lg_code | pref | county | city | ward | machiaza_id | oaza_cho | chome | koaza    | block | block_id | rsdt_num | rsdt_id | rsdt_num2 | rsdt2_id | rsdt_addr_flg | prc_num1 | prc_num2 | prc_num3 | prc_id          | lat               | lon                | coordinate_level   |
|-----------------------------|-------|---------------------------------|---------------------|--------------------|---------|------|--------|------|------|-------------|----------|-------|----------|-------|----------|----------|---------|-----------|----------|---------------|----------|----------|----------|-----------------|-------------------|--------------------|--------------------|
| 大阪市中央区上町Ｃ‐３                 | 0.79  | 大阪府大阪市中央区上町C‐3                  | C‐3                 | machiaza_detail    | 271284  | 大阪府  |        | 大阪市  | 中央区  | 0072000     | 上町       |       |          |       |          |          |         |           |          | 1             |          |          |          |                 | 34.677534         | 135.520976         | machiaza_detail    |
| 大阪市北区天神橋2丁目北2番6号            | 0.67  | 大阪府大阪市北区天神橋二丁目北2-6              | 北2-6                | machiaza_detail    | 271276  | 大阪府  |        | 大阪市  | 北区   | 0014002     | 天神橋      | 二丁目   |          |       |          |          |         |           |          | 1             |          |          |          |                 | 34.696499         | 135.512382         | machiaza_detail    |
| 大阪市鶴見区諸口5丁目浜6番12号           | 0.69  | 大阪府大阪市鶴見区諸口五丁目浜6-12             | 浜6-12               | machiaza_detail    | 271241  | 大阪府  |        | 大阪市  | 鶴見区  | 0009005     | 諸口       | 五丁目   |          |       |          |          |         |           |          | 1             |          |          |          |                 | 34.70344          | 135.583694         | machiaza_detail    |
| 大阪市中央区久太郎町４丁目渡辺6号           | 0.74  | 大阪府大阪市中央区久太郎町四丁目渡辺6             | 渡辺6                 | machiaza_detail    | 271284  | 大阪府  |        | 大阪市  | 中央区  | 0047004     | 久太郎町     | 四丁目   |          |       |          |          |         |           |          | 1             |          |          |          |                 | 34.680897         | 135.499051         | machiaza_detail    |
| 大阪市天王寺区堀越町アベノ地下街8号          | 0.8   | 大阪府大阪市天王寺区堀越町アベノ地下街8            | アベノ地下街8             | machiaza_detail    | 271098  | 大阪府  |        | 大阪市  | 天王寺区 | 0023000     | 堀越町      |       |          |       |          |          |         |           |          | 1             |          |          |          |                 | 34.649512         | 135.513902         | machiaza_detail    |
| 京都市東山区本町22丁目500番地           | 0.58  | 京都府京都市東山区本町二十二丁目500             |                     | parcel             | 261050  | 京都府  |        | 京都市  | 東山区  | 0178022     | 本町       | 二十二丁目 |          |       |          |          |         |           |          | 0             | 500      |          |          | 005000000000000 | 34.970593         | 135.771006         | machiaza_detail    |
| 北海道勇払郡安平町字安平番外地             | 0.94  | 北海道勇払郡安平町安平番外地                  | 番外地                 | machiaza_detail    | 015857  | 北海道  | 勇払郡    | 安平町  |      | 0001000     | 安平       |       |          |       |          |          |         |           |          | 0             |          |          |          |                 | 42.816856         | 141.82393          | machiaza_detail    |
| 龍ケ崎市3710番地                  | 0.55  | 茨城県龍ケ崎市3710                     | 3710                | city               | 082082  | 茨城県  |        | 龍ケ崎市 |      |             |          |       |          |       |          |          |         |           |          |               |          |          |          |                 | 35.911594         | 140.182265         | city               |
| 龍ケ崎市寺後3710番地                | 0.62  | 茨城県龍ケ崎市寺後3710                   | 寺後3710              | city               | 082082  | 茨城県  |        | 龍ケ崎市 |      |             |          |       |          |       |          |          |         |           |          |               |          |          |          |                 | 35.911594         | 140.182265         | city               |
| 龍ヶ崎市寺後3626-1                | 0.74  | 茨城県龍ケ崎市寺後3626-1                 | 寺後3626-1            | city               | 082082  | 茨城県  |        | 龍ケ崎市 |      |             |          |       |          |       |          |          |         |           |          |               |          |          |          |                 | 35.911594         | 140.182265         | city               |
| 長野県諏訪郡下諏訪町4613番地8           | 0.89  | 長野県諏訪郡下諏訪町4613-8                | 4613-8              | city               | 203611  | 長野県  | 諏訪郡    | 下諏訪町 |      |             |          |       |          |       |          |          |         |           |          |               |          |          |          |                 | 36.069577         | 138.08006800000004 | city               |
| 長野県上伊那郡南箕輪村4825-1           | 1     | 長野県上伊那郡南箕輪村4825-1               | 4825-1              | city               | 203858  | 長野県  | 上伊那郡   | 南箕輪村 |      |             |          |       |          |       |          |          |         |           |          |               |          |          |          |                 | 35.872853         | 137.975084         | city               |
| 長野県東筑摩郡生坂村5493-2            | 1     | 長野県東筑摩郡生坂村5493-2                | 5493-2              | city               | 204480  | 長野県  | 東筑摩郡   | 生坂村  |      |             |          |       |          |       |          |          |         |           |          |               |          |          |          |                 | 36.425234         | 137.927484         | city               |
| 長野県上伊那郡宮田村98番地              | 0.86  | 長野県上伊那郡宮田村98                    | 98                  | city               | 203882  | 長野県  | 上伊那郡   | 宮田村  |      |             |          |       |          |       |          |          |         |           |          |               |          |          |          |                 | 35.768882         | 137.944209         | city               |
| 神奈川県綾瀬市無番地                  | 1     | 神奈川県綾瀬市無番地                      | 無番地                 | city               | 142182  | 神奈川県 |        | 綾瀬市  |      |             |          |       |          |       |          |          |         |           |          |               |          |          |          |                 | 35.437161         | 139.426348         | city               |
| 東京都八丈島八丈町大賀郷2551番地2         | 1     | 東京都八丈島八丈町大賀郷2551番地2             | 東京都八丈島八丈町大賀郷2551番地2 | unknown            |         |      |        |      |      |             |          |       |          |       |          |          |         |           |          |               |          |          |          |                 |                   |                    | unknown            |
| 北海道紋別郡湧別町南兵村１区              | 0.93  | 北海道紋別郡湧別町南兵村一区                  |                     | machiaza_detail    | 015598  | 北海道  | 紋別郡    | 湧別町  |      | 0030000     | 南兵村一区    |       |          |       |          |          |         |           |          | 0             |          |          |          |                 | 44.110838         | 143.568026         | machiaza_detail    |
| 札幌市白石区南郷通6丁目北2-1            | 0.79  | 北海道札幌市白石区南郷通六丁目北2-1             |                     | residential_detail | 011045  | 北海道  |        | 札幌市  | 白石区  | 0052111     | 南郷通      |       | 六丁目北     | 2     | 002      | 1        | 001     |           |          | 1             |          |          |          |                 | 43.041920729      | 141.408207007      | residential_detail |
| 十日町市本町1丁目上1番地18             | 0.65  | 新潟県十日町市本町一丁目上1-18               |                     | parcel             | 152102  | 新潟県  |        | 十日町市 |      | 0194101     | 本町       |       | 一丁目上     |       |          |          |         |           |          | 0             | 1        | 18       |          | 000010001800000 | 37.127460576      | 138.758006602      | parcel             |
| 新潟県十日町市本町６の一丁目３８１－１         | 0.9   | 新潟県十日町市本町六の一丁目381-1             |                     | parcel             | 152102  | 新潟県  |        | 十日町市 |      | 0278001     | 本町六の     | 一丁目   |          |       |          |          |         |           |          | 0             | 381      | 1        |          | 003810000100000 | 37.137775376      | 138.762715474      | parcel             |
| 厚岸郡厚岸町太田５の通り２３番地１           | 0.69  | 北海道厚岸郡厚岸町太田五の通り23-1             |                     | parcel             | 016624  | 北海道  | 厚岸郡    | 厚岸町  |      | 0008000     | 太田五の通り   |       |          |       |          |          |         |           |          | 0             | 23       | 1        |          | 000230000100000 | 43.093640356      | 144.787720223      | parcel             |
| 新潟市西区五十嵐2の町8050番地           | 0.67  | 新潟県新潟市西区五十嵐二の町8050              | 8050                | machiaza_detail    | 151076  | 新潟県  |        | 新潟市  | 西区   | 0008000     | 五十嵐二の町   |       |          |       |          |          |         |           |          | 0             |          |          |          |                 | 37.869439         | 138.936116         | machiaza_detail    |
| 京都市上京区日暮通丸太町下がる4-802-3      | 0.79  | 京都府京都市上京区西院町日暮通丸太町下がる4-802-3    | 下がる4-802-3          | machiaza_detail    | 261025  | 京都府  |        | 京都市  | 上京区  | 0182124     | 西院町      |       | 日暮通丸太町   |       |          |          |         |           |          | 0             |          |          |          |                 | 35.018827         | 135.746811         | machiaza_detail    |
| 京都市上京区堀川下立売上る4－55           | 0.77  | 京都府京都市上京区堀川町下立売上る4-55           | 下立売上る4-55           | machiaza_detail    | 261025  | 京都府  |        | 京都市  | 上京区  | 0494000     | 堀川町      |       |          |       |          |          |         |           |          | 0             |          |          |          |                 | 35.021228         | 135.733689         | machiaza_detail    |
| 京都市中京区柳馬場通夷川上ル五丁目２３２番地の１    | 0.65  | 京都府京都市中京区五丁目柳馬場通夷川上る五丁目232-1    | 五丁目232-1            | machiaza_detail    | 261041  | 京都府  |        | 京都市  | 中京区  | 9008106     | 五丁目      |       | 柳馬場通夷川上る |       |          |          |         |           |          | 0             |          |          |          |                 | 35.015582         | 135.763968         | machiaza_detail    |
| 京都市中京区寺町通御池上る上本能寺前町488番地    | 0.65  | 京都府京都市中京区上本能寺前町寺町通御池上る上本能寺前町488 | 上本能寺前町488           | machiaza_detail    | 261041  | 京都府  |        | 京都市  | 中京区  | 0098104     | 上本能寺前町   |       | 寺町通御池上る  |       |          |          |         |           |          | 0             |          |          |          |                 | 35.011582         | 135.767914         | machiaza_detail    |
| 京都市上京区下立売通新町西入薮ノ内町          | 0.75  | 京都府京都市上京区春帯町下立売通新町西入薮ノ内町        | 薮ノ内町                | machiaza_detail    | 261025  | 京都府  |        | 京都市  | 上京区  | 0430104     | 春帯町      |       | 下立売通新町西入 |       |          |          |         |           |          | 0             |          |          |          |                 | 35.018688         | 135.75664700000002 | machiaza_detail    |
| 京都市上京区室町通下長者町通下ル近衛町38番地     | 0.71  | 京都府京都市上京区近衛町室町通下長者町通下ル近衛町38     | 通下ル近衛町38            | machiaza_detail    | 261025  | 京都府  |        | 京都市  | 上京区  | 0172106     | 近衛町      |       | 室町通下長者町  |       |          |          |         |           |          | 0             |          |          |          |                 | 35.021811         | 135.758151         | machiaza_detail    |
| 京都府京都市下京区油小路通木津屋橋通り上ル油小路282 | 0.97  | 京都府京都市下京区油小路町通木津屋橋通り上ル油小路282    | 通木津屋橋通り上ル油小路282     | machiaza_detail    | 261068  | 京都府  |        | 京都市  | 下京区  | 0007000     | 油小路町     |       |          |       |          |          |         |           |          | 0             |          |          |          |                 | 34.98830900000001 | 135.753716         | machiaza_detail    |
| 長野市若松町1028                  | 0.77  | 長野県長野市若松町1028                   | 若松町1028             | city               | 202011  | 長野県  |        | 長野市  |      |             |          |       |          |       |          |          |         |           |          |               |          |          |          |                 | 36.648631         | 138.1942866        | city               |
| 長野市新諏訪町６９０－３                | 0.74  | 長野県長野市新諏訪町690-3                 | 690-3               | machiaza_detail    | 202011  | 長野県  |        | 長野市  |      | 0000465     |          |       | 新諏訪町     |       |          |          |         |           |          | 0             |          |          |          |                 | 36.659675         | 138.170303         | machiaza_detail    |
| 大分市大石町1丁目3組                 | 0.79  | 大分県大分市大石町1丁目3組                  | 1丁目3組               | machiaza_detail    | 442011  | 大分県  |        | 大分市  |      | 0000369     |          |       | 大石町      |       |          |          |         |           |          | 0             |          |          |          |                 | 33.20835          | 131.584975         | machiaza_detail    |
| 大分県中津市二ノ丁本丸                 | 0.84  | 大分県中津市二丁目丁本丸                    | 丁本丸                 | machiaza_detail    | 442038  | 大分県  |        | 中津市  |      | 0057002     |          | 二丁目   |          |       |          |          |         |           |          | 1             |          |          |          |                 | 33.585834         | 131.190968         | city               |
| 北海道雨竜郡秩父別町字秩父別２０８５番地（２条１丁目） | 0.97  | 北海道雨竜郡秩父別町秩父別2085番地（2条1丁目）      | 2085番地（2条1丁目）       | machiaza_detail    | 014346  | 北海道  | 雨竜郡    | 秩父別町 |      | 0000101     |          |       | 秩父別      |       |          |          |         |           |          | 0             |          |          |          |                 | 43.770886         | 141.961089         | machiaza_detail    |
| 北海道雨竜郡秩父別町4 1 0 1 番地（２条２丁目） | 1     | 北海道雨竜郡秩父別町4 1 0 1 番地（2条2丁目）     | 4 1 0 1 番地（2条2丁目）   | city               | 014346  | 北海道  | 雨竜郡    | 秩父別町 |      |             |          |       |          |       |          |          |         |           |          |               |          |          |          |                 | 43.767            | 141.957896         | city               |
| 北海道雨竜郡雨竜町字尾白利加88番地38        | 0.85  | 北海道雨竜郡雨竜町尾白利加88-38              |                     | parcel             | 014362  | 北海道  | 雨竜郡    | 雨竜町  |      | 0000128     |          |       | 尾白利加     |       |          |          |         |           |          | 0             | 88       | 38       |          | 000880003800000 | 43.646040074      | 141.889758691      | parcel             |
| 雨竜郡雨竜町第8町内                  | 0.7   | 北海道雨竜郡雨竜町第八町内                   |                     | machiaza_detail    | 014362  | 北海道  | 雨竜郡    | 雨竜町  |      | 0007000     | 第八町内     |       |          |       |          |          |         |           |          | 0             |          |          |          |                 | 43.644744         | 141.888333         | machiaza_detail    |
| 大阪市北区中之島1丁目3番20号            | 0.67  | 大阪府大阪市北区中之島一丁目3-20              |                     | residential_detail | 271276  | 大阪府  |        | 大阪市  | 北区   | 0050001     | 中之島      | 一丁目   |          | 3     | 003      | 20       | 020     |           |          | 1             |          |          |          |                 | 34.693870178      | 135.50127668700003 | residential_detail |

**Comment by maskatsum** [comment]
> 東京都八丈島八丈町大賀郷2551番地2

```
[
  {
    "query": {
      "input": "東京都八丈島八丈町大賀郷2551番地2"
    },
    "result": {
      "output": "東京都八丈町大賀郷2551-2",
      "other": "2551-2",
      "score": 0.74,
      "match_level": "machiaza_detail",
      "coordinate_level": "machiaza_detail",
      "lat": 33.120906,
      "lon": 139.766238,
      "lg_code": "134015",
      "machiaza_id": "0002000",
      "rsdt_addr_flg": 0,
      "blk_id": null,
      "rsdt_id": null,
      "rsdt2_id": null,
      "prc_id": null,
      "pref": "東京都",
      "county": null,
      "city": "八丈町",
      "ward": null,
      "oaza_cho": "大賀郷",
      "chome": null,
      "koaza": null,
      "blk_num": null,
      "rsdt_num": null,
      "rsdt_num2": null,
      "prc_num1": null,
      "prc_num2": null,
      "prc_num3": null
    },
    "debug": {
      "pref_key": 5859431,
      "city_key": 3627089287,
      "town_key": 1988000794,
      "spendTime": "0.01"
    }
  }
]
```

**Comment by maskatsum** [comment]
番地が`Ｃ‐３` なんて特殊なケースも対応済み。

```
[
  {
    "query": {
      "input": "大阪市中央区上町Ｃ‐３"
    },
    "result": {
      "output": "大阪府大阪市中央区上町C-3",
      "other": null,
      "score": 0.72,
      "match_level": "residential_detail",
      "coordinate_level": "residential_detail",
      "lat": 34.67722339,
      "lon": 135.520750783,
      "lg_code": "271284",
      "machiaza_id": "0072000",
      "rsdt_addr_flg": 1,
      "blk_id": "903",
      "rsdt_id": "003",
      "rsdt2_id": null,
      "prc_id": null,
      "pref": "大阪府",
      "county": null,
      "city": "大阪市",
      "ward": "中央区",
      "oaza_cho": "上町",
      "chome": null,
      "koaza": null,
      "blk_num": "C",
      "rsdt_num": 3,
      "rsdt_num2": null,
      "prc_num1": null,
      "prc_num2": null,
      "prc_num3": null
    },
    "debug": {
      "pref_key": 5859296,
      "city_key": 3596324079,
      "town_key": 3627301589,
      "rsdtblk_key": 3096349312,
      "rsdtdsp_key": 1857324621,
      "spendTime": "0.01"
    }
  }
]
```
