### ISSUE TITLE
マッチングレベルについて

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#11]
https://github.com/digital-go-jp/abr-geocoder/blob/01bec959e1149629fccbf1fbe5d1360fcd3184c8/README.ja.md?plain=1#L144-L151

0→1→2→3→`7`?→`8`

`4`,`5`,`6` は何を意味するのでしょうか。もし無いならなぜでしょうか。

**Comment by koswatana** [comment]
今後、地番対応をする可能性があるのでリザーブしてます

**Comment by maskatsum** [comment]
なるほど、そういうケースの場合、数字ではなく文字列のが拡張性があるので良いです。

例えば「〇〇郡」はリストに入っていないですね。`郡` は複数の市町村から構成される行政区域の単位で、今の数字のレベルで言うと、`1` と `2` の中間に当たります。数字にしてしまうと、このように問題があるときにすぐに躓いてしまいます。

-------------

世界中の住所をサポートしている Google Maps Geocoding APIの場合、こんな表現をします。

- country
- administrative_area_level_1
- administrative_area_level_2
- administrative_area_level_3
- locality
- route
- street_number

... etc

https://developers.google.com/maps/documentation/geocoding/requests-geocoding?hl=ja#Types

これに倣って、こんな感じはどうでしょう。

| level | 説明 |
| ----- | ----|
| unknown | 都道府県も判別できなかった |
| prefecture | 都道府県まで判別できた |
| administrative_area_1 | 区、郡まで判別できた |
| administrative_area_2 | 市区町村まで判別できた |
| local_area1 | 町字まで判別できた |
| route | 住居表示の街区までの判別ができた。 |
| street | 住居表示の街区符号・住居番号までの判別ができた |

使う単語は要検討ですが、`〇〇_1`, `〇〇_2`, とすることで拡張性があります

**Comment by koswatana** [comment]
V2の設計で検討

**Comment by maskatsum** [comment]
これ今回のリファクタリングで、実現できますが、どうしますか？
v2まで延ばしますか？

**Comment by koswatana** [comment]
@maskatsum 
v2で他の対応と合わせて設計したいので、v2で検討します

**Comment by maskatsum** [comment]
https://github.com/digital-go-jp/abr-geocoder/blob/d2e11bd8c0c008ac60de644c311e89ccc1591c12/src/domain/matchLevel.enum.ts#L1-L19

数字で同じ意味合いをキープしつつ、コード中では区別しやすくするために定数値化で対応しました
