### ISSUE TITLE
入力データに /* ... */ が含まれている場合は、コメントとして扱う機能

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#111]
（主に開発用として）JavaScriptなどと同じように、`/* ... */` で複数行のコメントアウトをできるようにしたい。

**Comment by koswatana** [comment]
現行実装（v3）でのコメント除去挙動を確認しました。事実として記録します。

- **単一行内の `/* ... */`** は除去され、除去後の住所が正しくジオコーディングされます（例：`東京都千代田区紀尾井町1-3 /* 行内コメント */` → `東京都千代田区紀尾井町1-3`）。
- 一方、**改行をまたぐ複数行コメント**（`/*` と `*/` が別々の行にある形）は未対応です。`match` は入力を行単位で処理するため、コメント開始・終了が別行にあると各行が個別の住所として扱われます。

本 issue が求めた「複数行のコメントアウト」は現状未実装です（開発補助用途・優先度は低め）。対応を進める場合は再オープンしてください。
