### ISSUE TITLE
Macでのインストール問題

### ISSUE THREAD

**Issue by weiy1005** [digital-go-jp/abr-geocoder#116]
ソフトをほとんどインストールしていない、まっさらなMacで
`$ npm install @digital-go-jp/abr-geocoder`
コマンドでインストールしたらabrgコマンドが使えなかったです。

npmのグローバルインストールだとabrgが使えるようになったので、
ローカルインストール時のパスの設定方法を書いてもらえると助かります。
`$ npm install -g @digital-go-jp/abr-geocoder`

**Comment by maskatsum** [comment]
`npx abrg ` で動きませんでしょか？

**Comment by maskatsum** [comment]
v2.0.0 では動くことを確認済みです。
ローカルインストールについても説明を記述しました。
フィードバックを頂き、ありがとうございました。

https://github.com/digital-go-jp/abr-geocoder/blob/main/README.ja.md#%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB
