### ISSUE TITLE
レジストリカタログのデータ構造変更に伴うパッチ

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#118]
# 概要

ジオコーダーのデータ元である[レジストリカタログ](https://catalog.registries.digital.go.jp/rc/dataset/) のデータ構造が変化したため、それに対応するためのパッチを作成する

## 説明

基本的には CSVファイルのフィールド名の対応だけで動くと思う

**Comment by koswatana** [comment]
対応バッチをマージしたのでClose
https://github.com/digital-go-jp/abr-geocoder/pull/119
