### ISSUE TITLE
大字・町なし小字ありのパターンでマッチングできない

### ISSUE THREAD

**Issue by gt-r-isobe** [digital-go-jp/abr-geocoder#122]
調達案件「アドレス・ベース・レジストリの利活用を支援するジオコーディングツール群に関する調査研究」からの報告

- 入力：北海道空知郡上砂川町下鶉南二条1-3-2
- 正規化結果：北海道空知郡上砂川町, マッチングレベル2
  ```
  {"query":{"input":"北海道空知郡上砂川町下鶉南二条1-3-2"},"result":{"output":"北海道空知郡上砂川町下鶉南二条1-3-2","matching_level":2,"lg_code":null,"pref":"北海道","city":"空知郡上砂川町","machiaza":null,"machiaza_id":null,"blk_num":null,"blk_id":null,"rsdt_num":null,"rsdt_id":null,"rsdt_num2":null,"rsdt2_id":null,"prc_num1":null,"prc_num2":null,"prc_num3":null,"prc_id":null,"other":"下鶉南二条1-3-2","lat":null,"lon":null}}
  ```

アドレスBRには小字（大字・町なし）として「下鶉」が整備されているが、このアドレスとマッチングできない。

**Comment by maskatsum** [comment]
開発中のv2で試した結果。

```json
[
  {
    "query": {
      "input": "北海道空知郡上砂川町下鶉南二条1-3-2"
    },
    "result": {
      "output": "北海道空知郡上砂川町下鶉南二条1-3-2",
      "score": 1,
      "other": "南二条1-3-2",
      "match_level": "machiaza",
      "lg_code": "014257",
      "pref": "北海道",
      "county": "空知郡",
      "city": "上砂川町",
      "ward": null,
      "machiaza_id": "0000101",
      "oaza_cho": null,
      "chome": null,
      "koaza": "下鶉",
      "block": null,
      "block_id": null,
      "rsdt_num": null,
      "rsdt_id": null,
      "rsdt_num2": null,
      "rsdt2_id": null,
      "prc_num1": null,
      "prc_num2": null,
      "prc_num3": null,
      "prc_id": null
    }
  }
]

```

**Comment by maskatsum** [comment]
v2.0.0 で検証。前回よりも精度高くマッチングできています。

```
[
  {
    "query": {
      "input": "北海道空知郡上砂川町下鶉南二条1-3-2"
    },
    "result": {
      "output": "北海道空知郡上砂川町下鶉南二条1-3-2",
      "other": "南二条1-3-2",
      "score": 1,
      "match_level": "machiaza_detail",
      "coordinate_level": "machiaza_detail",
      "lat": 43.478589,
      "lon": 141.952469,
      "lg_code": "014257",
      "machiaza_id": "0000101",
      "rsdt_addr_flg": 0,
      "blk_id": null,
      "rsdt_id": null,
      "rsdt2_id": null,
      "prc_id": null,
      "pref": "北海道",
      "county": "空知郡",
      "city": "上砂川町",
      "ward": null,
      "oaza_cho": null,
      "chome": null,
      "koaza": "下鶉",
      "blk_num": null,
      "rsdt_num": null,
      "rsdt_num2": null,
      "prc_num1": null,
      "prc_num2": null,
      "prc_num3": null
    }
  }
]
```

**Comment by zero3kw** [comment]
北海道空知郡上砂川町下鶉南二条がデータ整備でなくなったので、北海道空知郡上砂川町緑が丘をテストケースに追加

% duckdb -markdown ./abrg.duckdb "SELECT * FROM cache_basic WHERE standardized_address LIKE '%空知郡上砂川町%'"                                                 
| categories | pref_code | lg_code | machiaza_id | rsdt_addr_flg |  pref  | county |   city   | ward | kyoto_street |  oaza_cho  | chome | koaza  | machiaza_dist |  standardized_address  |
|------------|----------:|---------|-------------|--------------:|--------|--------|----------|------|--------------|------------|-------|--------|---------------|------------------------|
| town       | 1         | 014257  | 0000108     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | NULL       | NULL  | 本町   | NULL          | 空知郡上砂川町本町     |
| town       | 1         | 014257  | 0006000     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | 字文珠     | NULL  | NULL   | NULL          | 空知郡上砂川町文珠     |
| town       | 1         | 014257  | 0000111     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | NULL       | NULL  | 鶉本町 | NULL          | 空知郡上砂川町鶉本町   |
| town       | 1         | 014257  | 0004000     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | 字西山     | NULL  | NULL   | NULL          | 空知郡上砂川町西山     |
| town       | 1         | 014257  | 0000106     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | NULL       | NULL  | 東町   | NULL          | 空知郡上砂川町東町     |
| town       | 1         | 014257  | 0000105     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | NULL       | NULL  | 東山   | NULL          | 空知郡上砂川町東山     |
| town       | 1         | 014257  | 0002000     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | 字上砂川   | NULL  | NULL   | NULL          | 空知郡上砂川町上砂川   |
| town       | 1         | 014257  | 0000101     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | NULL       | NULL  | 下鶉   | NULL          | 空知郡上砂川町下鶉     |
| town       | 1         | 014257  | 0000103     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | NULL       | NULL  | 中町   | NULL          | 空知郡上砂川町中町     |
| town       | 1         | 014257  | 0005000     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | 字東奈井江 | NULL  | NULL   | NULL          | 空知郡上砂川町東奈井江 |
| town       | 1         | 014257  | 0000102     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | NULL       | NULL  | 中央   | NULL          | 空知郡上砂川町中央     |
| town       | 1         | 014257  | 0000107     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | NULL       | NULL  | 東鶉   | NULL          | 空知郡上砂川町東鶉     |
| town       | 1         | 014257  | 0000109     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | NULL       | NULL  | 緑が丘 | NULL          | 空知郡上砂川町緑ケ丘   |
| town       | 1         | 014257  | 0001000     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | 字鶉       | NULL  | NULL   | NULL          | 空知郡上砂川町鶉       |
| town       | 1         | 014257  | 0000110     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | NULL       | NULL  | 鶉     | NULL          | 空知郡上砂川町鶉       |
| town       | 1         | 014257  | 0000104     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | NULL       | NULL  | 朝駒   | NULL          | 空知郡上砂川町朝駒     |
| town       | 1         | 014257  | 0003000     | 0             | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | 字上砂川町 | NULL  | NULL   | NULL          | 空知郡上砂川町上砂川町 |
| city       | 1         | 014257  | NULL        | NULL          | 北海道 | 空知郡 | 上砂川町 | NULL | NULL         | NULL       | NULL  | NULL   | NULL          | 空知郡上砂川町         |
