### ISSUE TITLE
半角カタカナでマッチングできない

### ISSUE THREAD

**Issue by gt-r-isobe** [digital-go-jp/abr-geocoder#124]
調達案件「アドレス・ベース・レジストリの利活用を支援するジオコーディングツール群に関する調査研究」からの報告

- 入力：長野県長野市篠ﾉ井布施高田200
- 正規化結果：長野県長野市
  ```
  {"query":{"input":"長野県長野市篠ﾉ井布施高田200"},"result":{"output":"長野県長野市篠ﾉ井布施高田200","matching_level":2,"lg_code":null,"pref":"長野県","city":"長野市","machiaza":null,"machiaza_id":null,"blk_num":null,"blk_id":null,"rsdt_num":null,"rsdt_id":null,"rsdt_num2":null,"rsdt2_id":null,"prc_num1":null,"prc_num2":null,"prc_num3":null,"prc_id":null,"other":"篠ﾉ井布施高田200","lat":null,"lon":null}}
  ```

アドレスBRには大字・町として「篠ノ井布施高田」が整備されているが、このアドレスとマッチングできない。

**Comment by koswatana** [comment]
v2-rcでの結果
```
[
  {
    "query": {
      "input": "長野県長野市篠ﾉ井布施高田200"
    },
    "result": {
      "output": "長野県長野市篠ノ井布施高田200",
      "score": 0.94,
      "other": null,
      "match_level": "parcel",
      "lg_code": "202011",
      "pref": "長野県",
      "county": null,
      "city": "長野市",
      "ward": null,
      "machiaza_id": "0121000",
      "oaza_cho": "篠ノ井布施高田",
      "chome": null,
      "koaza": null,
      "blk_num": null,
      "blk_id": null,
      "rsdt_num": null,
      "rsdt_id": null,
      "rsdt_num2": null,
      "rsdt2_id": null,
      "rsdt_addr_flg": 0,
      "prc_num1": "200",
      "prc_num2": null,
      "prc_num3": null,
      "prc_id": "002000000000000",
      "lat": 36.58047500000001,
      "lon": 138.143281,
      "coordinate_level": "machiaza_detail"
    }
  }
]
```

**Comment by maskatsum** [comment]
v2.0.0 で検証。

`篠ﾉ井`, `篠の井`, `篠ノ井`, `篠之井`, 全部できます！

| input            | output           | other | score | match_level | coordinate_level | lat               | lon        | lg_code | machiaza_id | rsdt_addr_flg | blk_id | rsdt_id | rsdt2_id | prc_id          | pref | county | city | ward | oaza_cho | chome | koaza | blk_num | rsdt_num | rsdt_num2 | prc_num1 | prc_num2 | prc_num3 |
|------------------|------------------|-------|-------|-------------|------------------|-------------------|------------|---------|-------------|---------------|--------|---------|----------|-----------------|------|--------|------|------|----------|-------|-------|---------|----------|-----------|----------|----------|----------|
| 篠ﾉ井布施高田200       | 長野県長野市篠ノ井布施高田200 |       | 0.57  | parcel      | machiaza_detail  | 36.58047500000001 | 138.143281 | 202011  | 0121000     | 0             |        |         |          | 002000000000000 | 長野県  |        | 長野市  |      | 篠ノ井布施高田  |       |       |         |          |           | 200      |          |          |
| 篠の井布施高田200       | 長野県長野市篠ノ井布施高田200 |       | 0.57  | parcel      | machiaza_detail  | 36.58047500000001 | 138.143281 | 202011  | 0121000     | 0             |        |         |          | 002000000000000 | 長野県  |        | 長野市  |      | 篠ノ井布施高田  |       |       |         |          |           | 200      |          |          |
| 篠ノ井布施高田200       | 長野県長野市篠ノ井布施高田200 |       | 0.63  | parcel      | machiaza_detail  | 36.58047500000001 | 138.143281 | 202011  | 0121000     | 0             |        |         |          | 002000000000000 | 長野県  |        | 長野市  |      | 篠ノ井布施高田  |       |       |         |          |           | 200      |          |          |
| 篠之井布施高田200       | 長野県長野市篠ノ井布施高田200 |       | 0.57  | parcel      | machiaza_detail  | 36.58047500000001 | 138.143281 | 202011  | 0121000     | 0             |        |         |          | 002000000000000 | 長野県  |        | 長野市  |      | 篠ノ井布施高田  |       |       |         |          |           | 200      |          |          |
| 長野県長野市篠ﾉ井布施高田200 | 長野県長野市篠ノ井布施高田200 |       | 0.94  | parcel      | machiaza_detail  | 36.58047500000001 | 138.143281 | 202011  | 0121000     | 0             |        |         |          | 002000000000000 | 長野県  |        | 長野市  |      | 篠ノ井布施高田  |       |       |         |          |           | 200      |          |          |
