### ISSUE TITLE
町字マスター（フルセット）の利用

### ISSUE THREAD

**Issue by gt-r-isobe** [digital-go-jp/abr-geocoder#125]
調達案件「アドレス・ベース・レジストリの利活用を支援するジオコーディングツール群に関する調査研究」からの報告

仕様確定版(v2)で追加された町字マスター（フルセット）の利用（外字・別名称でのジオコーディング）に対応する。

**Comment by maskatsum** [comment]
これは何でしたっけ

**Comment by koswatana** [comment]
[データフォーマット（仕様確定版）（Excel／98KB）](https://www.digital.go.jp/assets/contents/node/basic_page/field_ref_resources/3d996df3-f87c-4439-b474-c0fbbf3ddad8/31267348/20240115_policies_base_registry_format_01.xlsx)（2024年1月15日更新） で町字テーブルを拡張した町字フルセットテーブルが追加されました

07町字フルセットのシート
> 注3：地方自治法260条に基づく町字とは別に、通称名が住所・所在地の表示のため普及している場合等には、大字・町名、小字名に通称名を収録し得る。大字・町の階層が通称の場合（小字の階層は空欄または小字の階層にも通称を収録）、大字・町の階層が通称でなく小字の階層が通称の場合、を想定している。なお、試験公開版では「このデータセットでは京都の通り名の収録は想定しない」としていたが、小字名に通り名を格納し、小字名_通称コードに2をセットする。大字・町名に大字を収録するので、表示に使う場合には順番を逆転させる必要がある。

**Comment by wf9a5m75** [comment]
すみませんが、具体的例を示してもらえますか?

**Comment by maskatsum** [comment]
どうやら、京都の通り名に対応、という話かな。

**Comment by koswatana** [comment]
DB整備と関わるのでpendingでよいです

**Comment by koswatana** [comment]
小字に通称コード2で通り名が入っている場合は、大字の前に小字の文字列を表示する必要がある

**Comment by maskatsum** [comment]
次のバージョンで、京都の通り名に対応する（ように頑張る）
DBの構造が少し変化する

**Comment by koswatana** [comment]
小字名_通称コード(koaza_aka_code)は`町字マスター（フルセット）`だけでなく`町字マスター`にも入ってました
![image](https://github.com/user-attachments/assets/416e1191-dbfa-404e-8113-609d8e6effb6)
なので京都通り名対応で`町字マスター（フルセット）`に対応は必須ではありません

**Comment by maskatsum** [comment]
koaza_aka_code には、develop branchで対応済
