### ISSUE TITLE
同一大字・町・丁目に住居表示実施区域と未実施区域が併存する場合の対応

### ISSUE THREAD

**Issue by gt-r-isobe** [digital-go-jp/abr-geocoder#126]
調達案件「アドレス・ベース・レジストリの利活用を支援するジオコーディングツール群に関する調査研究」からの報告

当該案件で地番データのジオコーディングに対応したが、標記の条件が考慮できていないため、これに対応する。
- SQLiteに片方のレコードしか格納できていない。
- 住居表示実施区域のデータと未実施区域のデータ（＝地番）の両方を検索するようにできていない。

**Comment by koswatana** [comment]
> SQLiteに片方のレコードしか格納できていない。
town テーブルのユニークインデックスが実装では（v1 のまま） ("lg_code", "machiaza_id") となっており、データフォーマット（仕様確定版）で PK に指定されている rsdt_addr_flg が含まれていないため

**Comment by koswatana** [comment]
`rsdt_addr_flg`を追加したのでclose

```
CREATE TABLE "town" (
  "town_key" INTEGER PRIMARY KEY,
  "city_key" INTEGER,
  "machiaza_id" TEXT,
  "oaza_cho" TEXT,
  "chome" TEXT,
  "koaza" TEXT,
  "rsdt_addr_flg" INTEGER,

  -- mt_town_pos_prefXX から結合
  "rep_lat" REAL DEFAULT null,
  "rep_lon" REAL DEFAULT null
)
```
