### ISSUE TITLE
`update-check`コマンドの戻り値について

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#13]
https://github.com/digital-go-jp/abr-geocoder/blob/01bec959e1149629fccbf1fbe5d1360fcd3184c8/README.ja.md?plain=1#L42

となっていますが、使う側からすると、`CKANに新しいデータが存在する場合` と `ローカルのデータを確認できなかった場合` は異なるエラーコードを返して欲しいです

**Comment by koswatana** [comment]
たしかに今後、sqlite以外の外部DBへの接続の可能性を考慮すると異なるエラーコードにしておいたほうがよさそうです

**Comment by koswatana** [comment]
V2の設計で検討

**Comment by maskatsum** [comment]
複数のDBに対応するなら、https://typeorm.io/ を使うと良いです。
SQLの自由度は下がりますが、対応するDBの数が上がります。

**Comment by koswatana** [comment]
https://github.com/digital-go-jp/abr-geocoder/issues/99
以下に修正
```
新しいデータがあるとき、終了ステータスは0
新しいデータがないとき、終了ステータスは1
```
`CKANに新しいデータが存在する場合` と `ローカルのデータを確認できなかった場合` は異なるエラーコードを返すは対応する
