### ISSUE TITLE
discuss: 地番の枝番が存在しない場合にどうするか

### ISSUE THREAD

**Issue by koswatana** [digital-go-jp/abr-geocoder#130]
枝番の`1`が存在しないのか
`春日部市大字八丁目３５３番地` + `１`だと精度が下がる
`春日部市大字八丁目３５３番地`は存在するので`parcel`までヒットさせて、`"other": " -1"`としたい

```json
[
  {
    "query": {
      "input": "春日部市大字八丁目３５３番地１"
    },
    "result": {
      "output": "埼玉県春日部市八丁目353-1",
      "other": "353-1",
      "score": 0.54,
      "match_level": "machiaza_detail",
      "coordinate_level": "machiaza_detail",
      "lat": 35.995717,
      "lon": 139.772713,
      "lg_code": "112143",
      "machiaza_id": "0069000",
      "rsdt_addr_flg": 0,
      "blk_id": null,
      "rsdt_id": null,
      "rsdt2_id": null,
      "prc_id": null,
      "pref": "埼玉県",
      "county": null,
      "city": "春日部市",
      "ward": null,
      "oaza_cho": "八丁目",
      "chome": null,
      "koaza": null,
      "blk_num": null,
      "rsdt_num": null,
      "rsdt_num2": null,
      "prc_num1": null,
      "prc_num2": null,
      "prc_num3": null
    }
  }
]
```

春日部市大字八丁目３５３番地 にすると`parcel`でヒットする
```json
[
  {
    "query": {
      "input": "春日部市大字八丁目３５３番地"
    },
    "result": {
      "output": "埼玉県春日部市八丁目353",
      "other": null,
      "score": 0.5,
      "match_level": "parcel",
      "coordinate_level": "machiaza_detail",
      "lat": 35.995717,
      "lon": 139.772713,
      "lg_code": "112143",
      "machiaza_id": "0069000",
      "rsdt_addr_flg": 0,
      "blk_id": null,
      "rsdt_id": null,
      "rsdt2_id": null,
      "prc_id": "003530000000000",
      "pref": "埼玉県",
      "county": null,
      "city": "春日部市",
      "ward": null,
      "oaza_cho": "八丁目",
      "chome": null,
      "koaza": null,
      "blk_num": null,
      "rsdt_num": null,
      "rsdt_num2": null,
      "prc_num1": "353",
      "prc_num2": null,
      "prc_num3": null
    }
  }
]
```

**Comment by koswatana** [comment]
住居表示も可能性あり

**Comment by wf9a5m75** [comment]
すみませんが、もう少しテストケースを作っていただけますか

**Comment by maskatsum** [comment]
<img width="939" alt="Screenshot 2024-08-01 at 12 31 23 AM" src="https://github.com/user-attachments/assets/5c9b592d-55a8-4f30-902e-161f6e3fe9b8">

DBに枝番がないので `353-1` にはマッチしないのは、意図した設計です。

> "other": " -1"としたい

バグじゃないですね。要望ですね

**Comment by maskatsum** [comment]
<img width="692" alt="Screenshot 2024-08-01 at 12 37 07 AM" src="https://github.com/user-attachments/assets/e37d2cc1-ccb3-42cb-a4a9-fccc9993f013">

例えば、どこかの `250-1` から `250-4` があるとき、存在しない枝番 `250-100` を入力した場合、どのレコードに当てればよいのでしょうかね。

**Comment by maskatsum** [comment]
以前、逆パターンで議論はしたと思います。

`250` のレコードがない場合、`250-1` に当てるのが正しいのか、当てないのが正しいのか。
結論として、「当てない」になったはずです。

なので、`250-100` の `100` が存在しない場合、「当てない」が現時点では正しい動作になります。

**Comment by maskatsum** [comment]
Parcel で当たらないので、1つ上の段階の `machiaza_detail` で結果を返すことになり、精度が落ちます。
なので、バグではないです。

「当てたい」なら当てたいで良いですが、ルールが必要です。

**Comment by koswatana** [comment]
そっか、これは`machiaza`, `machiaza_detail`や`residential`とは性質が異なりますね
地番は階層構造とは限らないので、今の挙動が正しいです

**Comment by maskatsum** [comment]
じゃあ close しますー

**Comment by koswatana** [comment]
現行実装（v3）の挙動と、本 discuss の論点について事実と考察を記録します。

### 現行挙動（`abrg match`）

| 入力 | matched_address | match_level | other |
|---|---|---|---|
| 埼玉県春日部市大字八丁目353番地 | 埼玉県春日部市八丁目353 | parcel | なし |
| 埼玉県春日部市大字八丁目353番地1 | 埼玉県春日部市八丁目 | machiaza_detail | `353-1` |

`353番地`（枝番なし）は parcel まで到達し、`353番地1`（存在しない枝番）は machiaza に落ちて `353-1` が未マッチになります。本 issue の提案（枝番が無い場合に基底地番 `353` へヒットさせ `other:" -1"` とする）は現状では採られていません。

### 考察

住居表示と地番では、この「基底へのフォールバック」の意味合いが異なります。

- **住居表示**：街区符号は実在の街区（area）を表すため、住居番号が無くても街区レベルに落とすことには一定の意味がある。
- **地番**：`353` と `353-1` は**必ずしも隣接せず、まったく別の土地を指すことがある**。存在しない `353-1` を基底の `353` に丸めると、無関係な土地を指す誤りになりうる。

このため、地番で枝番が存在しないケースを基底地番へフォールバックさせず machiaza に留める現行挙動は、誤指示を避ける観点で妥当と考えられます。据え置きとしますが、方針を再検討する場合は再オープンしてください。
