### ISSUE TITLE
石川県七尾市の小字

### ISSUE THREAD

**Issue by koswatana** [digital-go-jp/abr-geocoder#134]
十二支が正しくマッチングしない

```
% abrg ./test.txt -f csv | cut -d, -f1,2,3,4,5
"石川県七尾市下町子","石川県七尾市下町子",,1,machiaza_detail <- OK
"石川県七尾市下町巳","石川県七尾市下町巳","巳",1,machiaza_detail <- NG
"石川県七尾市下町戌","石川県七尾市下町戌","戌",1,machiaza_detail  <- NG
"石川県七尾市下町戊","石川県七尾市下町戊",,1,machiaza_detail <- OK
```

文字の種類がわからないのでtown tableに入っているデータを以下に

| town_key   | city_key    | machiaza_id | oaza_cho | chome | koaza | rsdt_addr_flg | rep_lat | rep_lon |
|------------|-------------|-------------|----------|-------|-------|---------------|---------|---------|
| 104264336  | 3819206177  | 59147       | 下町     |       | 子    | 0             |         |         |
| 1304277235 | 3819206177  | 59144       | 下町     |       | 己    | 0             |         |         |
| 777687191  | 3819206177  | 59151       | 下町     |       | 戊    | 0             |         |         |

---
# 検証結果

- 新字、旧字対応追加かと思ったら類似する小字が存在した
- なのでこの動作は正しい
  - 石川県七尾市下町にあるのは
    - `巳(ミ)`でなく`己(キ)`
    - `戊(イヌ)`でなく`戊(ボ)`
- 新字旧字ではなく、OCR等で間違える可能性のある文字、類字
- 七尾市の場合、同一`oaza_cho`には類字が存在しないが、存在する場合は逆に対応してしまうと正しくマッチしない可能性がある

**Comment by koswatana** [comment]
`子丑寅卯辰巳午未申酉戌亥`他の町字にも入っていそうなので確認したい
![image](https://github.com/user-attachments/assets/95e8ca2f-6deb-49e9-a33a-b9702eb35492)

**Comment by maskatsum** [comment]
メモ
https://news.mynavi.jp/article/20130702-a064/

**Comment by koswatana** [comment]
```
SELECT DISTINCT koaza, koaza_kana
FROM town
WHERE city = "七尾市" AND koaza <> '' AND LENGTH(koaza) = 1
ORDER BY koaza_kana;
```

十二支 | ABRの小字 | diff
-- | -- | --
子 | 子 | FALSE
丑 | 丑 | FALSE
寅 | 寅 | FALSE
卯 | 卯 | FALSE
辰 | 辰 | FALSE
巳 | 巳 | FALSE
午 | 午 | FALSE
未 | 未 | FALSE
申 | 申 | FALSE
酉 | 酉 | FALSE
戌 | 戌 | FALSE
亥 | 亥 | FALSE

**Comment by koswatana** [comment]
```
SELECT DISTINCT city, oaza_cho, oaza_cho_kana, koaza, koaza_kana
FROM town
WHERE city = "七尾市"
AND(
 koaza LIKE '巳' OR
 koaza LIKE '己' OR
 koaza LIKE '戊' OR
 koaza LIKE '戌'
 )
ORDER BY koaza_kana;
```

city | oaza_cho | oaza_cho_kana | koaza | koaza_kana
-- | -- | -- | -- | --
七尾市 | 中島町塩津 | ナカジママチシオツ | 戌 | イヌ
七尾市 | 藤橋町 | フジハシマチ | 戌 | イヌ
七尾市 | 矢田町 | ヤタマチ | 戌 | イヌ
七尾市 | 吉田町 | ヨシタマチ | 戌 | イヌ
七尾市 | 大野木町 | オオノギマチ | 己 | キ
七尾市 | 下町 | シモマチ | 己 | キ
七尾市 | 千野町 | チノマチ | 己 | キ
七尾市 | 中島町小牧 | ナカジママチオマキ | 己 | キ
七尾市 | 中島町河内 | ナカジママチカワチ | 己 | キ
七尾市 | 西三階町 | ニシミカイマチ | 己 | キ
七尾市 | 大野木町 | オオノギマチ | 戊 | ボ
七尾市 | 下町 | シモマチ | 戊 | ボ
七尾市 | 千野町 | チノマチ | 戊 | ボ
七尾市 | 殿町 | トノマチ | 戊 | ボ
七尾市 | 中島町上畠 | ナカジママチウワバタケ | 戊 | ボ
七尾市 | 中島町小牧 | ナカジママチオマキ | 戊 | ボ
七尾市 | 中島町河内 | ナカジママチカワチ | 戊 | ボ
七尾市 | 中島町土川 | ナカジママチツチカワ | 戊 | ボ
七尾市 | 中島町鳥越 | ナカジママチトリゴエ | 戊 | ボ
七尾市 | 西三階町 | ニシミカイマチ | 戊 | ボ
七尾市 | 熊淵町 | クマブチマチ | 巳 | ミ
七尾市 | 中島町塩津 | ナカジママチシオツ | 巳 | ミ
七尾市 | 藤橋町 | フジハシマチ | 巳 | ミ
七尾市 | 南藤橋町 | ミナミフジハシマチ | 巳 | ミ
七尾市 | 矢田町 | ヤタマチ | 巳 | ミ
七尾市 | 吉田町 | ヨシタマチ | 巳 | ミ

**Comment by koswatana** [comment]
石川県七尾市下町にあるのは
- `巳(ミ)`でなく`己(キ)`
- `戊(イヌ)`でなく`戊(ボ)`
なので
https://github.com/digital-go-jp/abr-geocoder/issues/134#issue-2440688107
の動作は正しい

**Comment by koswatana** [comment]
OCRで処理したら間違えそう

**Comment by koswatana** [comment]
七尾市には1546種類の小字が存在する
```
> SELECT COUNT(DISTINCT koaza) FROM town WHERE city_key="3819206177" AND koaza <> '' ORDER BY koaza
1546
```
