### ISSUE TITLE
テストの作成

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#138]
- 開発リソースと期間の問題で、テストコードが作成できていない。
- Jest でテストコードを書く。
- ESLint も導入する

**Comment by koswatana** [comment]
ユニットテストだけでなくブラックボックステストもしたいなと考えてます
出力ファイルのdiffをとるくらいのシンプルなやつでもいいかなと

**Comment by maskatsum** [comment]
システムテストですね。はい、それも予定しています。

**Comment by silenvx** [comment]
@maskatsum 
https://github.com/digital-go-jp/abr-geocoder/pull/153
importで@があった場合でもテストが動くようなpull requestを発行しました

**Comment by maskatsum** [comment]
現状、コードカバレッジが53%とまだまだ不足しているが、ESLint / 単体テスト / e2eテストは導入できたので、一旦クローズする。

https://github.com/digital-go-jp/abr-geocoder/commit/75e402c9f61c69061ba2a531065cb6442bef2eeb#commitcomment-147936336
