### ISSUE TITLE
まだまだ精度に問題あり

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#15]
いくつか試してみて、気付いたものです。
ちょっとまだ精度が低いなー、という感じがします。

------------------

京都の住所は難しい
```
echo "京都府京都市東山区大和大路通正面下る大和大路2" | abr-geocoder normalize --format=json - | jq .
[
  {
    "pref": "京都府",
    "city": "京都市東山区",
    "lg_code": "261050",
    "town": "",
    "other": "大和大路通正面下る大和大路2",
    "lat": null,
    "lon": null,
    "level": 2
  }
]
```

----------

志布志市 市役所 有明支所ですから、もっと精度高く出したいですね！

![Screenshot 2023-06-20 at 10 50 26 AM](https://github.com/digital-go-jp/abr-geocoder/assets/122842582/2260547e-fbbb-44d4-9cc2-c8d1ada42e04)

```
echo "鹿児島県志布志市有明町野井倉1756" | abr-geocoder normalize --format=json - | jq .
[
  {
    "pref": "鹿児島県",
    "city": "志布志市",
    "lg_code": "462217",
    "town": "有明町野井倉",
    "town_id": "0002000",
    "other": "1756",
    "lat": 31.482451000000005,
    "lon": 131.04758,
    "level": 3
  }
]
```

-----------

志布志市 市役所 松山支所ですから、もっと精度高く出したいですね！

```
echo "鹿児島県志布志市松山町新橋268" | abr-geocoder normalize --format=json - | jq .
[
  {
    "pref": "鹿児島県",
    "city": "志布志市",
    "lg_code": "462217",
    "town": "松山町新橋",
    "town_id": "0015000",
    "other": "268",
    "lat": 31.588354,
    "lon": 131.044958,
    "level": 3
  }
]
```

-----------

`千葉県浦安市舞浜2-11` は 「ディズニーアンバサダーホテル」です。
https://www.olc.co.jp/ja/tdr/profile/ambassador.html

![Screenshot 2023-06-20 at 10 44 41 AM](https://github.com/digital-go-jp/abr-geocoder/assets/122842582/34a9157a-0a8a-403e-a439-19f56ceb58f3)

`35.641178,139.880872` (level 7) で、`さすがに精度高いなー`、と思いきや、
```
echo "千葉県浦安市舞浜2-11" | abr-geocoder normalize --format=json - | jq .
[
  {
    "pref": "千葉県",
    "city": "浦安市",
    "lg_code": "122271",
    "town": "舞浜二丁目",
    "town_id": "0018002",
    "other": "",
    "lat": 35.641178,
    "lon": 139.880872,
    "level": 7,
    "blk": "11",
    "blk_id": "011"
  }
]
```

実際の位置関係とずれた位置関係で表示されます。ちょっとズレが大きいかなー。

![Screenshot 2023-06-20 at 10 38 55 AM](https://github.com/digital-go-jp/abr-geocoder/assets/122842582/dbffe4dc-6278-4c6a-a394-b1eb2f756efd)

**Comment by maskatsum** [comment]
郵便局ですから、精度高く行きたいですねー。

https://www.post.japanpost.jp/cgi-shiten_search/shiten.php?id=10296

![Screenshot 2023-06-20 at 10 49 28 AM](https://github.com/digital-go-jp/abr-geocoder/assets/122842582/6d4642b7-51c6-4b00-bc83-02451e7dc3f1)

```
echo "静岡県下田市2丁目4-26" | abr-geocoder normalize --format=json - | jq .
[
  {
    "pref": "静岡県",
    "city": "下田市",
    "lg_code": "222194",
    "town": "二丁目",
    "town_id": "0000002",
    "other": "4-26",
    "lat": null,
    "lon": null,
    "level": 3
  }
]
```

**Comment by maskatsum** [comment]
御所市役所です

https://www.city.gose.nara.jp

![Screenshot 2023-06-20 at 10 52 12 AM](https://github.com/digital-go-jp/abr-geocoder/assets/122842582/58579e25-be4b-4faa-be88-bcb328ef9706)

```
echo "奈良県御所市1番地の3" | abr-geocoder normalize --format=json - | jq .
[
  {
    "pref": "奈良県",
    "city": "御所市",
    "lg_code": "292087",
    "town": "",
    "other": "1番地の3",
    "lat": null,
    "lon": null,
    "level": 2
  }
]
```

**Comment by maskatsum** [comment]
`大阪市`から始めると、精度がガタ落ちですね。

https://www.water.go.jp/kansai/kansai/

![Screenshot 2023-06-20 at 10 55 16 AM](https://github.com/digital-go-jp/abr-geocoder/assets/122842582/aa9db81d-cf94-4375-a15a-eef7fdab26fe)

```
echo "大阪市中央区上町A-12" | abr-geocoder normalize --format=json - | jq .
[
  {
    "pref": "大阪府",
    "city": "",
    "town": "",
    "other": "市中央区上町A-12",
    "lat": null,
    "lon": null,
    "level": 1
  }
]
```

-------------

お、でもこれは精度高い！

```
echo "大阪府大阪市中央区上町A-12" | abr-geocoder normalize --format=json - | jq .
[
  {
    "pref": "大阪府",
    "city": "大阪市中央区",
    "lg_code": "271284",
    "town": "上町",
    "town_id": "0072000",
    "other": "A-12",
    "lat": 34.677534,
    "lon": 135.520976,
    "level": 3
  }
]
```
![Screenshot 2023-06-20 at 10 59 21 AM](https://github.com/digital-go-jp/abr-geocoder/assets/122842582/7041c748-459d-4874-80f8-096df33d6e34)

**Comment by maskatsum** [comment]
頑張った！けど、実務レベルではもう少し精度を上げたいところ。

```
echo "大阪府大阪市中央区久太郎町４丁目渡辺 渡辺3号" | abr-geocoder normalize --format=json - | jq .
[
  {
    "pref": "大阪府",
    "city": "大阪市中央区",
    "lg_code": "271284",
    "town": "久太郎町四丁目",
    "town_id": "0047004",
    "other": "渡辺 渡辺3号",
    "lat": 34.680897,
    "lon": 135.499051,
    "level": 3
  }
]
```
![Screenshot 2023-06-20 at 11 11 21 AM](https://github.com/digital-go-jp/abr-geocoder/assets/122842582/fcc12809-df97-43dd-a9b8-ea9e0d33ac44)

**Comment by maskatsum** [comment]
八街市立八街北中学校 の住所です。うーん、ちょっとズレが大きいですね

```
echo "千葉県八街市八街は18番地2" | abr-geocoder normalize --format=json - | jq .
[
  {
    "pref": "千葉県",
    "city": "八街市",
    "lg_code": "122301",
    "town": "八街は",
    "town_id": "0028000",
    "other": "18-2",
    "lat": 35.701601,
    "lon": 140.306522,
    "level": 3
  }
]
```
![Screenshot 2023-06-20 at 11 25 00 AM](https://github.com/digital-go-jp/abr-geocoder/assets/122842582/be7a0d29-5b54-4df9-912b-152532aad99c)

**Comment by maskatsum** [comment]
日本基督教団 長野教会 の住所です。だいぶ離れてますね

```
echo "長野県長野市南長野県町477-1" | abr-geocoder normalize --format=json - | jq .
[
  {
    "pref": "長野県",
    "city": "長野市",
    "lg_code": "202011",
    "town": "大字南長野",
    "town_id": "0231000",
    "other": "県町477-1",
    "lat": 36.649947,
    "lon": 138.184107,
    "level": 3
  }
]
```
![Screenshot 2023-06-20 at 11 33 13 AM](https://github.com/digital-go-jp/abr-geocoder/assets/122842582/bc39e403-23ce-4e74-af19-1ea803d75acd)

**Comment by koswatana** [comment]
まだABRが地番対応していないため、現状地番に関しては町字までのジオコーディングになっています

**Comment by maskatsum** [comment]
開発中のv2での結果。`奈良県御所市1番地の3`だけ、なんで精度が悪いんだ


| input                   | score | output                  | other   | match_level         | lg_code | pref | county | city | ward | machiaza_id | oaza_cho | chome | koaza | block | block_id | rsdt_num | rsdt_id | rsdt_num2 | rsdt2_id | rsdt_addr_flg | prc_num1 | prc_num2 | prc_num3 | prc_id          | lat          | lon           |
|-------------------------|-------|-------------------------|---------|---------------------|---------|------|--------|------|------|-------------|----------|-------|-------|-------|----------|----------|---------|-----------|----------|---------------|----------|----------|----------|-----------------|--------------|---------------|
| 鹿児島県志布志市有明町野井倉1756      | 1     | 鹿児島県志布志市有明町野井倉1756      |         | parcel              | 462217  | 鹿児島県 |        | 志布志市 |      | 0002000     | 有明町野井倉   |       |       |       |          |          |         |           |          | 0             | 1756     |          |          | 017560000000000 | 31.496100184 | 131.045437446 |
| 鹿児島県志布志市松山町新橋268        | 1     | 鹿児島県志布志市松山町新橋268        |         | parcel              | 462217  | 鹿児島県 |        | 志布志市 |      | 0015000     | 松山町新橋    |       |       |       |          |          |         |           |          | 0             | 268      |          |          | 002680000000000 | 31.576793183 | 131.040666652 |
| 千葉県浦安市舞浜2-11            | 0.77  | 千葉県浦安市舞浜二丁目11           |         | residential_block   | 122271  | 千葉県  |        | 浦安市  |      | 0018002     | 舞浜       | 二丁目   |       | 11    | 011      |          |         |           |          | 1             |          |          |          |                 | 35.641178    | 139.880872    |
| 静岡県下田市2丁目4-26           | 0.93  | 静岡県下田市二丁目4-26           | 4-26    | machiaza            | 222194  | 静岡県  |        | 下田市  |      | 0000002     |          | 二丁目   |       |       |          |          |         |           |          | 1             |          |          |          |                 |              |               |
| 奈良県御所市1番地の3             | 0.73  | 奈良県御所市1-3               | 1-3     | administrative_area | 292087  | 奈良県  |        | 御所市  |      |             |          |       |       |       |          |          |         |           |          |               |          |          |          |                 |              |               |
| 大阪市中央区上町A-12            | 0.8   | 大阪府大阪市中央区上町A-12         | A-12    | machiaza            | 271284  | 大阪府  |        | 大阪市  | 中央区  | 0072000     | 上町       |       |       |       |          |          |         |           |          | 1             |          |          |          |                 |              |               |
| 大阪府大阪市中央区上町A-12         | 1     | 大阪府大阪市中央区上町A-12         | A-12    | machiaza            | 271284  | 大阪府  |        | 大阪市  | 中央区  | 0072000     | 上町       |       |       |       |          |          |         |           |          | 1             |          |          |          |                 |              |               |
| 大阪府大阪市中央区久太郎町４丁目渡辺 渡辺3号 | 0.96  | 大阪府大阪市中央区久太郎町四丁目渡辺 渡辺3号 | 渡辺 渡辺3号 | machiaza            | 271284  | 大阪府  |        | 大阪市  | 中央区  | 0047004     | 久太郎町     | 四丁目   |       |       |          |          |         |           |          | 1             |          |          |          |                 |              |               |
| 千葉県八街市八街は18番地2          | 0.86  | 千葉県八街市八街は18-2           | 18-2    | machiaza            | 122301  | 千葉県  |        | 八街市  |      | 0028000     | 八街は      |       |       |       |          |          |         |           |          | 0             |          |          |          |                 |              |               |
| 長野県長野市南長野県町477-1        | 0.89  | 長野県長野市大字南長野県町477-1      | 県町477-1 | machiaza            | 202011  | 長野県  |        | 長野市  |      | 0231000     | 大字南長野    |       |       |       |          |          |         |           |          | 0             |          |          |          |                 |              |               |

**Comment by maskatsum** [comment]
v2.0.0 で検証
| input                   | output                  | other      | score | match_level        | coordinate_level   | lat          | lon           | lg_code | machiaza_id | rsdt_addr_flg | blk_id | rsdt_id | rsdt2_id | prc_id          | pref | county | city | ward | oaza_cho | chome | koaza | blk_num | rsdt_num | rsdt_num2 | prc_num1 | prc_num2 | prc_num3 |
|-------------------------|-------------------------|------------|-------|--------------------|--------------------|--------------|---------------|---------|-------------|---------------|--------|---------|----------|-----------------|------|--------|------|------|----------|-------|-------|---------|----------|-----------|----------|----------|----------|
| 京都府京都市東山区大和大路通正面下る大和大路2 | 京都府京都市東山区大和大路通正面下る大和大路2 | 通正面下る大和大路2 | 1     | machiaza           | city               | 34.997082    | 135.776282    | 261050  | 0202000     | -1            |        |         |          |                 | 京都府  |        | 京都市  | 東山区  | 大和大路     |       |       |         |          |           |          |          |          |
| 鹿児島県志布志市有明町野井倉1756      | 鹿児島県志布志市有明町野井倉1756      |            | 1     | parcel             | parcel             | 31.496100184 | 131.045437446 | 462217  | 0002000     | 0             |        |         |          | 017560000000000 | 鹿児島県 |        | 志布志市 |      | 有明町野井倉   |       |       |         |          |           | 1756     |          |          |
| 鹿児島県志布志市松山町新橋268        | 鹿児島県志布志市松山町新橋268        |            | 1     | parcel             | parcel             | 31.576793183 | 131.040666652 | 462217  | 0015000     | 0             |        |         |          | 002680000000000 | 鹿児島県 |        | 志布志市 |      | 松山町新橋    |       |       |         |          |           | 268      |          |          |
| 千葉県浦安市舞浜2-11            | 千葉県浦安市舞浜二丁目11           |            | 0.77  | residential_block  | residential_block  | 35.641178    | 139.880872    | 122271  | 0018002     | 1             | 011    |         |          |                 | 千葉県  |        | 浦安市  |      | 舞浜       | 二丁目   |       | 11      |          |           |          |          |          |
| 静岡県下田市2丁目4-26           | 静岡県下田市二丁目4-26           | -26        | 0.93  | residential_block  | residential_block  | 34.683979    | 138.944254    | 222194  | 0026002     | 1             | 004    |         |          |                 | 静岡県  |        | 下田市  |      |          | 二丁目   |       | 4       |          |           |          |          |          |
| 奈良県御所市1番地の3             | 奈良県御所市1-3               | 1-3        | 0.73  | city               | city               | 34.46334     | 135.740177    | 292087  |             |               |        |         |          |                 | 奈良県  |        | 御所市  |      |          |       |       |         |          |           |          |          |          |
| 大阪市中央区上町A-12            | 大阪府大阪市中央区上町A-12         |            | 0.8   | residential_detail | residential_detail | 34.67774141  | 135.521066831 | 271284  | 0072000     | 1             | 901    | 012     |          |                 | 大阪府  |        | 大阪市  | 中央区  | 上町       |       |       | A       | 12       |           |          |          |          |
| 大阪府大阪市中央区上町A-12         | 大阪府大阪市中央区上町A-12         |            | 1     | residential_detail | residential_detail | 34.67774141  | 135.521066831 | 271284  | 0072000     | 1             | 901    | 012     |          |                 | 大阪府  |        | 大阪市  | 中央区  | 上町       |       |       | A       | 12       |           |          |          |          |
| 大阪府大阪市中央区久太郎町４丁目渡辺 渡辺3号 | 大阪府大阪市中央区久太郎町四丁目渡辺 渡辺3号 |  渡辺3号      | 0.96  | residential_block  | residential_block  | 34.680827    | 135.498693    | 271284  | 0047004     | 1             | 901    |         |          |                 | 大阪府  |        | 大阪市  | 中央区  | 久太郎町     | 四丁目   |       | 渡辺      |          |           |          |          |          |
| 千葉県八街市八街は18番地2          | 千葉県八街市八街は18-2           | 18-2       | 0.86  | machiaza_detail    | machiaza_detail    | 35.701601    | 140.306522    | 122301  | 0028000     | 0             |        |         |          |                 | 千葉県  |        | 八街市  |      | 八街は      |       |       |         |          |           |          |          |          |
| 長野県長野市南長野県町477-1        | 長野県長野市大字南長野県町477-1      | 県町477-1    | 0.89  | machiaza_detail    | machiaza_detail    | 36.649947    | 138.184107    | 202011  | 0231000     | 0             |        |         |          |                 | 長野県  |        | 長野市  |      | 大字南長野    |       |       |         |          |           |          |          |          |

**Comment by maskatsum** [comment]
v2.0.0 の結果。良さそう。
ちゃんと「京都市 東山区総合庁舎」にピンが落ちる。

| input                   | output                  | other      | score | match_level        | coordinate_level   | lat          | lon           | lg_code | machiaza_id | rsdt_addr_flg | blk_id | rsdt_id | rsdt2_id | prc_id          | pref | county | city | ward | oaza_cho | chome | koaza | blk_num | rsdt_num | rsdt_num2 | prc_num1 | prc_num2 | prc_num3 |
|-------------------------|-------------------------|------------|-------|--------------------|--------------------|--------------|---------------|---------|-------------|---------------|--------|---------|----------|-----------------|------|--------|------|------|----------|-------|-------|---------|----------|-----------|----------|----------|----------|
| 京都府京都市東山区大和大路通正面下る大和大路2 | 京都府京都市東山区大和大路通正面下る大和大路2 | 通正面下る大和大路2 | 1     | machiaza           | city               | 34.997082    | 135.776282    | 261050  | 0202000     | -1            |        |         |          |                 | 京都府  |        | 京都市  | 東山区  | 大和大路     |       |       |         |          |           |          |          |          |

![Screenshot 2024-07-30 at 11 15 09 PM](https://github.com/user-attachments/assets/598b8c88-ce35-4dcd-b9f3-57b6078b8616)

**Comment by maskatsum** [comment]
v2.0.0 の結果。良さそう。
「志布志市役所 有明支所」と若干の誤差があるけど、それはデータの問題。住所の解析としては良さそう。

| input                   | output                  | other      | score | match_level        | coordinate_level   | lat          | lon           | lg_code | machiaza_id | rsdt_addr_flg | blk_id | rsdt_id | rsdt2_id | prc_id          | pref | county | city | ward | oaza_cho | chome | koaza | blk_num | rsdt_num | rsdt_num2 | prc_num1 | prc_num2 | prc_num3 |
|-------------------------|-------------------------|------------|-------|--------------------|--------------------|--------------|---------------|---------|-------------|---------------|--------|---------|----------|-----------------|------|--------|------|------|----------|-------|-------|---------|----------|-----------|----------|----------|----------|
| 鹿児島県志布志市有明町野井倉1756      | 鹿児島県志布志市有明町野井倉1756      |            | 1     | parcel             | parcel             | 31.496100184 | 131.045437446 | 462217  | 0002000     | 0             |        |         |          | 017560000000000 | 鹿児島県 |        | 志布志市 |      | 有明町野井倉   |       |       |         |          |           | 1756     |          |          |
![Screenshot 2024-07-30 at 11 19 24 PM](https://github.com/user-attachments/assets/418f20c3-5bf7-4f29-bc26-06ea11abd1a3)

**Comment by maskatsum** [comment]
v2.0.0 の結果。良さそう。
「志布志市 市役所 松山支所」も良さそう。

| input                   | output                  | other      | score | match_level        | coordinate_level   | lat          | lon           | lg_code | machiaza_id | rsdt_addr_flg | blk_id | rsdt_id | rsdt2_id | prc_id          | pref | county | city | ward | oaza_cho | chome | koaza | blk_num | rsdt_num | rsdt_num2 | prc_num1 | prc_num2 | prc_num3 |
|-------------------------|-------------------------|------------|-------|--------------------|--------------------|--------------|---------------|---------|-------------|---------------|--------|---------|----------|-----------------|------|--------|------|------|----------|-------|-------|---------|----------|-----------|----------|----------|----------|
| 鹿児島県志布志市松山町新橋268        | 鹿児島県志布志市松山町新橋268        |            | 1     | parcel             | parcel             | 31.576793183 | 131.040666652 | 462217  | 0015000     | 0             |        |         |          | 002680000000000 | 鹿児島県 |        | 志布志市 |      | 松山町新橋    |       |       |         |          |           | 268      |          |          |

![Screenshot 2024-07-30 at 11 22 54 PM](https://github.com/user-attachments/assets/36fed430-c8c7-454d-b024-994416634c20)

**Comment by maskatsum** [comment]
v2.0.0 の結果。ちゃんと「2丁目11」に当たっている


| input                   | output                  | other      | score | match_level        | coordinate_level   | lat          | lon           | lg_code | machiaza_id | rsdt_addr_flg | blk_id | rsdt_id | rsdt2_id | prc_id          | pref | county | city | ward | oaza_cho | chome | koaza | blk_num | rsdt_num | rsdt_num2 | prc_num1 | prc_num2 | prc_num3 |
|-------------------------|-------------------------|------------|-------|--------------------|--------------------|--------------|---------------|---------|-------------|---------------|--------|---------|----------|-----------------|------|--------|------|------|----------|-------|-------|---------|----------|-----------|----------|----------|----------|
| 千葉県浦安市舞浜2-11            | 千葉県浦安市舞浜二丁目11           |            | 0.77  | residential_block  | residential_block  | 35.641178    | 139.880872    | 122271  | 0018002     | 1             | 011    |         |          |                 | 千葉県  |        | 浦安市  |      | 舞浜       | 二丁目   |       | 11      |          |           |          |          |          |

![Screenshot 2024-07-30 at 11 25 43 PM](https://github.com/user-attachments/assets/7ae5db4b-e9db-4b9d-8c71-d50282cae2cc)

**Comment by maskatsum** [comment]
ちなみに「千葉県浦安市舞浜2-11」は「地番」もある、ということで、`target=parcel`のときの結果。

住所の解析としては良さそう。緯度経度は、`coordinate_level = machiaza_detail` なので、ズレは仕方ない。

| input        | output       | other | score | match_level | coordinate_level | lat       | lon                | lg_code | machiaza_id | rsdt_addr_flg | blk_id | rsdt_id | rsdt2_id | prc_id          | pref | county | city | ward | oaza_cho | chome | koaza | blk_num | rsdt_num | rsdt_num2 | prc_num1 | prc_num2 | prc_num3 | pref_key | city_key   | town_key   | parcel_key | rsdtblk_key | rsdtdsp_key | spend_time |
|--------------|--------------|-------|-------|-------------|------------------|-----------|--------------------|---------|-------------|---------------|--------|---------|----------|-----------------|------|--------|------|------|----------|-------|-------|---------|----------|-----------|----------|----------|----------|----------|------------|------------|------------|-------------|-------------|------------|
| 千葉県浦安市舞浜2-11 | 千葉県浦安市舞浜2-11 |       | 1     | parcel      | machiaza_detail  | 35.632144 | 139.88163500000002 | 122271  | 0018000     | 0             |        |         |          | 000020001100000 | 千葉県  |        | 浦安市  |      | 舞浜       |       |       |         |          |           | 2        | 11       |          | 5859398  | 3781184928 | 3695745622 | 1343684331 |             |             | 0.01       |

![Screenshot 2024-07-30 at 11 32 19 PM](https://github.com/user-attachments/assets/4d05292d-7416-477e-922e-16f6ca1f025d)

**Comment by maskatsum** [comment]
v2.0.0で検証。
下田郵便局は、なんでこんなに離れているんだ。

| input                   | output                  | other      | score | match_level        | coordinate_level   | lat          | lon           | lg_code | machiaza_id | rsdt_addr_flg | blk_id | rsdt_id | rsdt2_id | prc_id          | pref | county | city | ward | oaza_cho | chome | koaza | blk_num | rsdt_num | rsdt_num2 | prc_num1 | prc_num2 | prc_num3 |
|-------------------------|-------------------------|------------|-------|--------------------|--------------------|--------------|---------------|---------|-------------|---------------|--------|---------|----------|-----------------|------|--------|------|------|----------|-------|-------|---------|----------|-----------|----------|----------|----------|
| 静岡県下田市2丁目4-26           | 静岡県下田市二丁目4-26           | -26        | 0.93  | residential_block  | residential_block  | 34.683979    | 138.944254    | 222194  | 0026002     | 1             | 004    |         |          |                 | 静岡県  |        | 下田市  |      |          | 二丁目   |       | 4       |          |           |          |          |          |

![Screenshot 2024-07-30 at 11 40 13 PM](https://github.com/user-attachments/assets/283fb209-3946-45c5-9707-fa15a4c4b009)

**Comment by maskatsum** [comment]
地番モードで検索。そうか。地番なんだな。でも `coordinate_level = machiaza_detail` だから、緯度経度の精度はあまり期待できない


| input         | output        | other | score | match_level | coordinate_level | lat       | lon        | lg_code | machiaza_id | rsdt_addr_flg | blk_id | rsdt_id | rsdt2_id | prc_id          | pref | county | city | ward | oaza_cho | chome | koaza | blk_num | rsdt_num | rsdt_num2 | prc_num1 | prc_num2 | prc_num3 | pref_key | city_key   | town_key  | parcel_key | rsdtblk_key | rsdtdsp_key | spend_time |
|---------------|---------------|-------|-------|-------------|------------------|-----------|------------|---------|-------------|---------------|--------|---------|----------|-----------------|------|--------|------|------|----------|-------|-------|---------|----------|-----------|----------|----------|----------|----------|------------|-----------|------------|-------------|-------------|------------|
| 静岡県下田市2丁目4-26 | 静岡県下田市二丁目4-26 |       | 0.93  | parcel      | machiaza_detail  | 34.685286 | 138.943672 | 222194  | 0026002     | 1             |        |         |          | 000040002600000 | 静岡県  |        | 下田市  |      |          | 二丁目   |       |         |          |           | 4        | 26       |          | 5859397  | 3597474987 | 403618162 | 3579561965 |             |             | 0.02       |

**Comment by maskatsum** [comment]
v2.0.0で検証。おー、すごい。精度高い。

| input                   | output                  | other      | score | match_level        | coordinate_level   | lat          | lon           | lg_code | machiaza_id | rsdt_addr_flg | blk_id | rsdt_id | rsdt2_id | prc_id          | pref | county | city | ward | oaza_cho | chome | koaza | blk_num | rsdt_num | rsdt_num2 | prc_num1 | prc_num2 | prc_num3 |
|-------------------------|-------------------------|------------|-------|--------------------|--------------------|--------------|---------------|---------|-------------|---------------|--------|---------|----------|-----------------|------|--------|------|------|----------|-------|-------|---------|----------|-----------|----------|----------|----------|
| 大阪市中央区上町A-12            | 大阪府大阪市中央区上町A-12         |            | 0.8   | residential_detail | residential_detail | 34.67774141  | 135.521066831 | 271284  | 0072000     | 1             | 901    | 012     |          |                 | 大阪府  |        | 大阪市  | 中央区  | 上町       |       |       | A       | 12       |           |          |          |          |

![Screenshot 2024-07-30 at 11 53 29 PM](https://github.com/user-attachments/assets/051c8f5b-c242-4af1-8b15-568f31b96110)

**Comment by maskatsum** [comment]
v2.0.0で検証。「番地名が渡辺」というスーパレアな住所。
ちゃんと「渡辺 渡辺3号」の位置にピンが落ちる。

| input                   | output                  | other      | score | match_level        | coordinate_level   | lat          | lon           | lg_code | machiaza_id | rsdt_addr_flg | blk_id | rsdt_id | rsdt2_id | prc_id          | pref | county | city | ward | oaza_cho | chome | koaza | blk_num | rsdt_num | rsdt_num2 | prc_num1 | prc_num2 | prc_num3 |
|-------------------------|-------------------------|------------|-------|--------------------|--------------------|--------------|---------------|---------|-------------|---------------|--------|---------|----------|-----------------|------|--------|------|------|----------|-------|-------|---------|----------|-----------|----------|----------|----------|
| 大阪府大阪市中央区久太郎町４丁目渡辺 渡辺3号 | 大阪府大阪市中央区久太郎町四丁目渡辺 渡辺3号 |  渡辺3号      | 0.96  | residential_block  | residential_block  | 34.680827    | 135.498693    | 271284  | 0047004     | 1             | 901    |         |          |                 | 大阪府  |        | 大阪市  | 中央区  | 久太郎町     | 四丁目   |       | 渡辺      |          |           |          |          |          |

![Screenshot 2024-07-30 at 11 57 39 PM](https://github.com/user-attachments/assets/88d05389-5da9-4dd4-9894-f20743b35b7a)

**Comment by maskatsum** [comment]
v2.0.0 で検証。
うーん、これは v1 のときと変わらず。たぶんデータの問題かな。`18-2` がないっぽい

| input                   | output                  | other      | score | match_level        | coordinate_level   | lat          | lon           | lg_code | machiaza_id | rsdt_addr_flg | blk_id | rsdt_id | rsdt2_id | prc_id          | pref | county | city | ward | oaza_cho | chome | koaza | blk_num | rsdt_num | rsdt_num2 | prc_num1 | prc_num2 | prc_num3 |
|-------------------------|-------------------------|------------|-------|--------------------|--------------------|--------------|---------------|---------|-------------|---------------|--------|---------|----------|-----------------|------|--------|------|------|----------|-------|-------|---------|----------|-----------|----------|----------|----------|
| 千葉県八街市八街は18番地2          | 千葉県八街市八街は18-2           | 18-2       | 0.86  | machiaza_detail    | machiaza_detail    | 35.701601    | 140.306522    | 122301  | 0028000     | 0             |        |         |          |                 | 千葉県  |        | 八街市  |      | 八街は      |       |       |         |          |           |          |          |          |

**Comment by maskatsum** [comment]
v2.0.0 で検証。これも v1 から変化なし。たぶんデータかな。

| input                   | output                  | other      | score | match_level        | coordinate_level   | lat          | lon           | lg_code | machiaza_id | rsdt_addr_flg | blk_id | rsdt_id | rsdt2_id | prc_id          | pref | county | city | ward | oaza_cho | chome | koaza | blk_num | rsdt_num | rsdt_num2 | prc_num1 | prc_num2 | prc_num3 |
|-------------------------|-------------------------|------------|-------|--------------------|--------------------|--------------|---------------|---------|-------------|---------------|--------|---------|----------|-----------------|------|--------|------|------|----------|-------|-------|---------|----------|-----------|----------|----------|----------|
| 長野県長野市南長野県町477-1        | 長野県長野市大字南長野県町477-1      | 県町477-1    | 0.89  | machiaza_detail    | machiaza_detail    | 36.649947    | 138.184107    | 202011  | 0231000     | 0             |        |         |          |                 | 長野県  |        | 長野市  |      | 大字南長野    |       |       |         |          |           |          |          |          |

**Comment by maskatsum** [comment]
総じて、マッチングの精度は改善されている。データがないものは仕方ない。

**Comment by koswatana** [comment]
> v2.0.0 で検証。これも v1 から変化なし。たぶんデータかな。
> 
> input	output	other	score	match_level	coordinate_level	lat	lon	lg_code	machiaza_id	rsdt_addr_flg	blk_id	rsdt_id	rsdt2_id	prc_id	pref	county	city	ward	oaza_cho	chome	koaza	blk_num	rsdt_num	rsdt_num2	prc_num1	prc_num2	prc_num3
> 長野県長野市南長野県町477-1	長野県長野市大字南長野県町477-1	県町477-1	0.89	machiaza_detail	machiaza_detail	36.649947	138.184107	202011	0231000	0					長野県		長野市		大字南長野

小字に県町がない

![image](https://github.com/user-attachments/assets/6f3f9a52-d4db-4c22-a4db-277d7db12eaf)

**Comment by maskatsum** [comment]
データにないものは仕方ないですね。あくまでも DBにどれだけ正確に突合していくか、という話なので。
