### ISSUE TITLE
エッジケース：階数を含むケース

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#157]
`札幌市中央区南２条西１ー５ー２F` の正解は、`北海道札幌市中央区南二条西一丁目5 2F`
https://zenn.dev/sikkim/articles/bc86fbcac3a9fd

現時点では、`2F` の `2` までマッチングするので、`北海道札幌市中央区南二条西一丁目5-2 F` になってしまう

**Comment by maskatsum** [comment]
`2号室` でも同様のことが発生するのか。

**Comment by koswatana** [comment]
正しくは`一丁目5番`のデータに当てるはずが`一丁目5番2号`にあたってしまっているので座標が異なってしまう

**Comment by wf9a5m75** [comment]
これは解決できそう

**Comment by wf9a5m75** [comment]
developブランチで解決済み
