### ISSUE TITLE
小字が省略される場合

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#158]
こちらの記事によると、「小字が省略されるとき」と「省略不可なとき」がある
https://note.com/navitime_tech/n/ne71603fe4bf8

- `島根県出雲市大社町杵築東宮内195` と `島根県出雲市大社町杵築東195` は同じ

**Comment by maskatsum** [comment]
`島根県出雲市大社町杵築東宮内195` で処理をした場合、`koaza-transform.ts`の段階で `島根県出雲市大社町杵築東` までは判別している。
なので、`宮内195` と `195` だけを考慮すれば良い。

- `宮内195` でDBを検索すると parcelテーブルには見つからないので、`machiaza_detail` になる。
- `195` でDBを検索すると、見つかるので `parcel` になる。

```json
[
  {
    "query": {
      "input": "島根県出雲市大社町杵築東宮内195"
    },
    "result": {
      "output": "島根県出雲市大社町杵築東宮内195",
      "other": "宮内195",
      "score": 1,
      "match_level": "machiaza_detail",
      "coordinate_level": "machiaza_detail",
      "lat": 35.408443,
      "lon": 132.684868,
      "lg_code": "322032",
      "machiaza_id": "0085000",
      "rsdt_addr_flg": 0,
      "blk_id": null,
      "rsdt_id": null,
      "rsdt2_id": null,
      "prc_id": null,
      "pref": "島根県",
      "county": null,
      "city": "出雲市",
      "ward": null,
      "oaza_cho": "大社町杵築東",
      "chome": null,
      "koaza": null,
      "blk_num": null,
      "rsdt_num": null,
      "rsdt_num2": null,
      "prc_num1": null,
      "prc_num2": null,
      "prc_num3": null
    },
    "debug": {
      "pref_key": 5859396,
      "city_key": 3820322439,
      "town_key": 3230727189,
      "spendTime": "132.38"
    }
  },
  {
    "query": {
      "input": "島根県出雲市大社町杵築東195"
    },
    "result": {
      "output": "島根県出雲市大社町杵築東195",
      "other": null,
      "score": 1,
      "match_level": "parcel",
      "coordinate_level": "parcel",
      "lat": 35.402679688,
      "lon": 132.685615359,
      "lg_code": "322032",
      "machiaza_id": "0085000",
      "rsdt_addr_flg": 0,
      "blk_id": null,
      "rsdt_id": null,
      "rsdt2_id": null,
      "prc_id": "001950000000000",
      "pref": "島根県",
      "county": null,
      "city": "出雲市",
      "ward": null,
      "oaza_cho": "大社町杵築東",
      "chome": null,
      "koaza": null,
      "blk_num": null,
      "rsdt_num": null,
      "rsdt_num2": null,
      "prc_num1": "195",
      "prc_num2": null,
      "prc_num3": null
    },
    "debug": {
      "pref_key": 5859396,
      "city_key": 3820322439,
      "town_key": 3230727189,
      "parcel_key": 3806716743,
      "spendTime": "132.38"
    }
  }
]
```

**Comment by maskatsum** [comment]
@koswatana 

> 長野県長野市南長野県町477-1 
>> 小字に県町がない
https://github.com/digital-go-jp/abr-geocoder/issues/15#issuecomment-2259834846

これ、たぶん小字が省略されている、って話ですね。
技術的に「477-1」だけを抽出して、Parcelテーブルに当てに行くことはできます。
もしあれば、Parcelレベルになるので結果精度が向上されます。

このときに「小字」を最終結果に含めるかどうか、が問題になってきます。

```
{
    "query": {
      "input": "長野県長野市大字南長野県町477-1"
    },
    {
        "output": "長野県長野市大字南長野県町477-1"　←　ここに「県町」を含むかどうか (DB内には「県町」はない）
        ....
        "koaza": "県町"
    }
}
```

**Comment by maskatsum** [comment]
この方式で行くと、　`長野県長野市大字南長野あああああ477-1` でも同じようなことが発生します。


```
{
    "query": {
      "input": "長野県長野市大字南長野県町477-1"
    },
    {
        "output": "長野県長野市大字南長野477-1"　←　含めなければきれいな結果になる
        "output": "長野県長野市大字南長野あああああ477-1"　←　入力された文字を維持するなら、「あああああ」は残る
        ....
        "koaza": "あああああ"
    }
}
```

**Comment by maskatsum** [comment]
「正規化」の定義で考えた場合、どれが良いでしょうね

**Comment by maskatsum** [comment]
@koswatana さんによると、基盤小字（省略不可）と、非基盤小字（省略可）があるそうで、abrデータベースとしては両方持っているけれど、CSVとしては非基盤小字は出していない、とのこと。

個人的には、非基盤小字は出力結果から削除してよいのではないかと思う

**Comment by koswatana** [comment]
参考
町名の無い「龍ケ崎市○○○○番地」の住所表示について-小字は省略される-
https://www.city.ryugasaki.ibaraki.jp/shisei/gaiyo/jyuusyohyouki/2013081601149.html

**Comment by maskatsum** [comment]
ありがとうございます。では、　`長野県長野市大字南長野県町477-1` はどうでしょうか。

`県町` はDBに存在しないので、現在の実装では、parcelテーブルに当たりません。
しかし`県町`は 「省略できる小字だろうと推測して」を含めなければ `parcel` で当たります。つまり精度を高めることが可能です。

この場合、`非起番` は公開されていないので、コードとしては「残された数字の前にある文字は非起番であろう」と扱うことになります。
（つまりコードから見れば「県町」も「あああああ」も取り扱いとしては同じ）

それでも精度としては高める必要がない（現在の実装のままで良い）ということでしょうか？
（実装方針の確認だけなので、それならそれで良い）

**Comment by koswatana** [comment]
> 3. 非起番 情報を公開する

これは今後公開される可能性はゼロではないため、
> 1. 現在のまま
を維持します

**Comment by maskatsum** [comment]
承知です。方針が確認できたので、クローズしますねー。

**Comment by koswatana** [comment]
lg_code | machiaza_id | machiaza_type | pref | pref_kana | pref_roma | county | county_kana | county_roma | city | city_kana | city_roma | ward | ward_kana | ward_roma | oaza_cho | oaza_cho_kana | oaza_cho_roma | chome | chome_kana | chome_number | koaza | koaza_kana | koaza_roma | machiaza_dist | rsdt_addr_flg | rsdt_addr_mtd_code | oaza_cho_aka_flg | koaza_aka_code | oaza_cho_gsi_uncmn | koaza_gsi_uncmn | status_flg | wake_num_flg | efct_date | ablt_date | src_code | post_code | remarks | rep_lon | rep_lat
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
202011 | 0000264 | 3 | 長野県 | ナガノケン | Nagano |   |   |   | 長野市 | ナガノシ | Nagano-shi |   |   |   |   |   |   |   |   |   | 県町 | アガタマチ | Agatamachi |   | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 1947-04-17 |   | 0 | 3800838 |   | 138.183414 | 36.653119
202011 | 0000727 | 3 | 長野県 | ナガノケン | Nagano |   |   |   | 長野市 | ナガノシ | Nagano-shi |   |   |   |   |   |   |   |   |   | 南県町 | ミナミアガタマチ | Minamiagatamachi |   | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 1947-04-17 |   | 0 | 3800836 |   | 138.184331 | 36.649953

</body></html>
