### ISSUE TITLE
【質問】100件ほどの問い合わせで発生するエラーについて

### ISSUE THREAD

**Issue by m-hamada-hn** [digital-go-jp/abr-geocoder#161]
初めまして。質問はこちらでよろしいでしょうか。

100件ほどの住所を記述したテキストファイルを<inputFile>としてabrgを実行した際にヒープメモリエラーが発生しています（※エラー全文は末尾に記載）。原因の調査方法、または、対処方法をご教示頂きたく思います。

【環境】
OS：Ubuntu 20.04 LTS（Windows10のWSL上）
MemTotal：64GB
abrg --version：2.0.0

【現状】
・3種の--max-old-space-size（20480、30720、40960）で実行するもエラーに変化なし。
（※上記設定が反映されていることは、都度下記のコマンドで確認しました。
　　node -e 'console.log(Math.floor(v8.getHeapStatistics().heap_size_limit/1024/1024))'　）
・50件ほどの問い合わせではエラーが発生しないことを確認しました。

以上です。
よろしくお願い致します。

～～～以下、発生したエラー全文です。～～～
<--- Last few GCs --->

[483:0x7f8c80001620]    22447 ms: Scavenge 459.8 (493.1) -> 450.4 (496.3) MB, 52.87 / 0.00 ms  (average mu = 1.000, current mu = 1.000) allocation failure;
[483:0x7f8c80001620]    23177 ms: Scavenge 463.1 (496.3) -> 453.7 (497.1) MB, 673.51 / 0.00 ms  (average mu = 1.000, current mu = 1.000) allocation failure;
[483:0x7f8c80001620]    23525 ms: Scavenge 464.5 (497.1) -> 456.4 (497.1) MB, 315.77 / 0.00 ms  (average mu = 1.000, current mu = 1.000) allocation failure;

<--- JS stacktrace --->

FATAL ERROR: NewSpace::EnsureCurrentCapacity Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xb82d33 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [node]
 2: 0xef0c50 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 3: 0xef0f37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 4: 0x1102ad5  [node]
 5: 0x1141de9  [node]
 6: 0x1114c26 v8::internal::Heap::MarkCompact() [node]
 7: 0x111a27d v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*) [node]
 8: 0x111a76c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0x10f0a71 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0x10f1c05 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
11: 0x10ce326 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
12: 0x10bfa9c v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [node]
13: 0x10bfc04 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [node]
14: 0x13ef9bd v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate(v8::internal::Isolate*, int, v8::internal::AllocationType) [node]
15: 0x13efa63 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [node]
16: 0x1520673 v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [node]
17: 0x7f8bdfe99ef6
Aborted

**Comment by maskatsum** [comment]
ご連絡をいただきありがとうございます。
100件ですか。
サンプルデータを共有していただくことはできますか？

**Comment by m-hamada-hn** [comment]
お世話になります。
下記の通り添付致します。よろしくお願い致します。

[input_kouji_100.txt](https://github.com/user-attachments/files/16556098/input_kouji_100.txt)

**Comment by maskatsum** [comment]
ありがとうございます。検証してみます。

**Comment by maskatsum** [comment]
![Screenshot 2024-08-09 100047](https://github.com/user-attachments/assets/8be4f1db-a680-4cd5-bd9c-eab3f40c28e8)

まずは試してみたのですが、ちょっとまだ再現できないですね

**Comment by maskatsum** [comment]
@koswatana さん、再現できるかテストしていただけますでしょうか。

**Comment by koswatana** [comment]
私の環境でも再現しないですね
```
root@3ea8f2dbdcfd:/workspaces/abr-geocoder# git log -1
commit 6db6fe17e32b3965bff3476fc50166a82f9fae30 (HEAD -> main, origin/main, origin/HEAD)
Merge: 86a71db 10e23c9
Author: KosukeWATANABE <103909883+koswatana@users.noreply.github.com>
Date:   Wed Jul 31 14:11:09 2024 +0900

    Merge pull request #128 from digital-go-jp/v2-rc
    
    chore: update minimum required Node.js version to 20
root@3ea8f2dbdcfd:/workspaces/abr-geocoder# abrg --version
2.0.0
root@3ea8f2dbdcfd:/workspaces/abr-geocoder# abrg ./input_kouji_100.txt > /dev/null
root@3ea8f2dbdcfd:/workspaces/abr-geocoder# echo $?
0
```

**Comment by maskatsum** [comment]
@m-hamada-hn さん

ここ数日、別の問題を解決するためにデバッグしていましたが、似たようなログが出たときがMacでもありました。
コードがそれは無限ループに陥ったときですね。
これが起こる条件は、データが設計の想定外の場合です。
つまり、データに起因して起こります。

すみませんが、エラーが起きた当時の正確な100件のデータを共有していただけますか？
もし出来ないということでしたら、すみませんが、どの入力データなのかを特定してください。
よろしくお願いします

**Comment by m-hamada-hn** [comment]
@maskatsum @koswatana 

ご確認頂きありがとうございます。

> エラーが起きた当時の正確な100件のデータを共有していただけますか？

先日添付した「input_kouji_100.txt」でエラーが発生している状態です。

![image](https://github.com/user-attachments/assets/53bffe72-accd-4f19-b377-842f87566ec3)

なお、50件であればエラーが発生しないことを確認しました。

![image](https://github.com/user-attachments/assets/fcfd4bf1-f92a-481f-99db-5650eda07bcb)

「input_kouji_50.txt」は「input_kouji_100.txt」から50件削除したデータになります。
念のため添付させて頂きます。

[input_kouji_50.txt](https://github.com/user-attachments/files/16620072/input_kouji_50.txt)

> これが起こる条件は、データが設計の想定外の場合です。
> つまり、データに起因して起こります。

コウジ違い（麹、麴）の住所が連続している、というデータの内容は大差ないため
データ件数に起因するエラーだと考えておりました。

想定外のデータ、というのは具体的にどのようなデータになりますでしょうか。
文字コードや改行コードなどご教示頂けますと幸いです。

よろしくお願い致します。

**Comment by maskatsum** [comment]
@m-hamada-hn さん

今のところ、私も @koswatana さんのところでも再現しないので、同じデータで検証しても難しいと思います。
100件、1万件、5万件、500万件でテストをしていますので、データ量ではないとでしょう。
もし要因があるとすれば、そのテストに含まれていない文字が @m-hamada-hn さんのデータには含まれている、もしくは、環境的に CPU の種類に依る、など別の要因の可能性だと思っています。

とは言え、コードにバグがない、というわけではありません。次のバージョンに向けて、既にいくつものバグを修正しています。
お手数をおかけしますが、develop ブランチで試してみていただけますか？
https://github.com/digital-go-jp/abr-geocoder/tree/develop

**Comment by m-hamada-hn** [comment]
@maskatsum さん

お手数をおかけして大変申し訳ないのですが、developブランチのインストール方法をご教示頂けないでしょうか。
いくつかのコマンドを実行してみたのですが、いずれもエラーとなっています。

npm install -g @digital-go-jp/abr-geocoder#develop
npm install -g github:digital-go-jp/abr-geocoder#develop
npm install -g digital-go-jp/abr-geocoder#develop
npm install -g git+https://github.com/digital-go-jp/abr-geocoder.git#develop

**Comment by maskatsum** [comment]
Gitコマンドを使って、ソースコードからインストールする方法になります。

1. npmコマンドでインストールした abr-geocoder をアンイストール
```
npm uninstall -g @digital-go-jp/abr-geocoder
```

2. git clone で、リポジトリからコードを取得
```
git clone -b develop https://github.com/digital-go-jp/abr-geocoder

(以降、リポジトリのコードが更新されたら git pull で最新版を取得することが出来ます。バグを含んでいる可能性もあるので、注意してください）
git pull
```

3. 依存モジュールのインストール
```
cd abr-geocoder/
npm i
```

4. ビルド & リンク
```
npm run build
npm link
```

5. 確認
```
abrg
```

**Comment by m-hamada-hn** [comment]
@maskatsum さん

ありがとうございます。
確認結果は別途報告致します。

**Comment by m-hamada-hn** [comment]
@maskatsum さん

ご教示頂いた手順を【8/21 10:00頃】に実行し、developブランチを利用できるようになりました。ありがとうございました。
結果、先日お伝えした100件のデータはエラーなく実行完了することを確認致しました。

元々は１自治体分ほどの住所をまとめて処理したい思いがありますので、同じデータのコピペで件数を拡張してみたところ
3,000件ではエラーなく実行完了しましたが、1万件ほどでは途中でエラーとなり終了する（※）ことを確認致しました。
（※）エラーとなるまでの1,638件は出力されていました。

上記の通り、3,000件ではエラーが発生せず、また、エラーになったとしても途中までの結果は得られる事を
確認致しましたので、今回は入力ファイルを分割して実行しようかと考えておりますが、
何かのお役に立てば、と思いエラーの内容を下記の通り報告致します。

> $ abrg input_kouji_12k.txt output_kouji_12k.csv -f csv
 █████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 13% | 1638/12000  geocoding...TypeError [Error]: Cannot read properties of undefined (reading 'address')
    at NormalizeTransform._transform (/home/user/abrgc/develop/abr-geocoder/build/usecases/geocode/steps/normalize-transform.js:24:41)
    at Transform._write (node:internal/streams/transform:171:8)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at Readable.ondata (node:internal/streams/readable:1007:22)
    at Readable.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
    at Readable.push (node:internal/streams/readable:391:5)

> node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^
TypeError [Error]: Cannot read properties of undefined (reading 'address')
    at NormalizeTransform._transform (/home/user/abrgc/develop/abr-geocoder/build/usecases/geocode/steps/normalize-transform.js:24:41)
    at Transform._write (node:internal/streams/transform:171:8)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at Readable.ondata (node:internal/streams/readable:1007:22)
    at Readable.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
    at Readable.push (node:internal/streams/readable:391:5)

> Node.js v20.16.0

**Comment by maskatsum** [comment]
ありがとうございます。
エラーの内容から見るとデータに由来するように見られますが、詳細は分からないです。

お手数をおかけしますが、下記のコマンドの結果を教えていただけますでしょうか。

```
git log --format="%H" -n 1
```

**Comment by m-hamada-hn** [comment]
@maskatsum さん

ありがとうございます。下記の通り結果を報告致します。

48749ba5b37a0712d1fb342febf3c8fb291c709d

全文
`48749ba5b37a0712d1fb342febf3c8fb291c709d`

**Comment by maskatsum** [comment]
ありがとうございます。原因のデータがないので、検証が難しいのですが、csvファイルに改行を含むセルとかが入っていますでしょうか。

**Comment by m-hamada-hn** [comment]
@maskatsum さん

データを添付しておらず失礼しました。
確認しましたが、csvに改行を含むセル、はありませんでした。

何度か実行したところ、エラーが必ず1,638行目か3,276行目で発生していることを確認しました。
特に後者の結果では1,640行目のinputカラムが「長崎県長崎???麹屋町２－１９」となっていたので
異常な文字の混入が原因かと考えたのですが、テキストエディタでは正常に表示されており
比較ツール（WinMerge）ではエラーが発生していない行との差異が確認できませんでした。

[input_kouji_12k.txt](https://github.com/user-attachments/files/16686910/input_kouji_12k.txt)
[output_kouji_12k - 1638でエラー.csv](https://github.com/user-attachments/files/16686911/output_kouji_12k.-.1638.csv)
[output_kouji_12k - 3276でエラー.csv](https://github.com/user-attachments/files/16686912/output_kouji_12k.-.3276.csv)

また、下記２種のデータを作成して実行しても同じ結果となっています。

[input_kouji_2_10k.txt](https://github.com/user-attachments/files/16686908/input_kouji_2_10k.txt)
→input_kouji_12k.txtから、エラーが発生していない1、2行目のデータを抽出、コピペして10,000件としたデータ

[input_kouji_3_10k.txt](https://github.com/user-attachments/files/16686909/input_kouji_3_10k.txt)
→同、2行目のデータのみで10,000件としたデータ

ほかに必要な情報などございましたらご教示ください。

**Comment by maskatsum** [comment]
詳細に調べていただきありがとうございます。
なかなか興味深いレポートですね。非常に助かります。
検証の上、後日アップデートさせていただきます

**Comment by koswatana** [comment]
4,263,904件のデータを処理できたので件数ではなさそうですね
https://github.com/digital-go-jp/abr-geocoder/wiki/%E5%AE%9F%E8%A1%8C%E9%80%9F%E5%BA%A6%E3%83%A1%E3%83%A2

**Comment by koswatana** [comment]
@m-hamada-hn 
> 元々は１自治体分ほどの住所をまとめて処理したい
ちなみにデータの出典元って教えていただくことは可能でしょうか
自治体のどのようなシステムのデータでエラーが発生するのか知りたく

**Comment by maskatsum** [comment]
しばらく時間が開いてしまいまして申し訳ありません。
正直なところ、こちらの問題に関係しそうなバグフィックスは確認できていません。
ただどこで何が影響をしているのかは分からないので、大変お手数をおかけいたしますが、現在のdevelopブランチのコードで問題が再現するかどうか、ご確認いただけますでしょうか。

**Comment by maskatsum** [comment]
![Screenshot 2024-10-15 153627](https://github.com/user-attachments/assets/a7964ac7-a1a2-4e8e-a3b6-3e29e619b819)

> 特に後者の結果では1,640行目のinputカラムが「長崎県長崎???麹屋町２－１９」となっていたので

たしかに1640行目で文字化けが発生しますね。。。。

**Comment by m-hamada-hn** [comment]
ご無沙汰しております。
こちらでは状況に進展あり、ちょうどご連絡差し上げようと考えていたところでした。

結論から申し上げますと、解決しました。
Windows上に環境を構築（※）することで、エラーが発生しないことを確認しました。

（※）今回構築した環境
- 　OS：Windows10、および、11
- 　node：20.18.0
- 　npm：10.8.2
- 　git：2.47.0.windows.1
- 　abrg：2.0.0

ただ、以前の環境（WSL上のUbuntu）でのdevelop版では変わらず、同様のエラーが発生しています。
（※今しがた「git pull」した上で先日報告したデータを用いて数度実行しました。）

**Comment by maskatsum** [comment]
早速検証していただき、ありがとうございます。
(ちなみに v2.0 と v2.1 (develop branch) だとDBの構造が変わります)

こちらだとエラーがどうにも発生しないので、難しいですね。。。
プロファイリングを行える方法を調べてみますので、すみませんがもう少し検証にお付き合いください（またアップデートします）

**Comment by m-hamada-hn** [comment]
> ちなみに v2.0 と v2.1 (develop branch) だとDBの構造が変わります
develop版導入後にデータの更新を行っておりませんでした。
「abrg update-check」して再確認してみます。

検証について承知致しました。
具体的な手順などお示し頂けますと幸いです。

**Comment by maskatsum** [comment]
> develop版導入後にデータの更新を行っておりませんでした。

すみません、新しいディレクトリで `abrg download` からやっていただくと良いかと思います。
日本全国をダウンロードすると大変なので、長崎県長崎市だけなら、`abrg download -c 422011` としていただければ、長崎市だけをダウンロードしてきます

**Comment by m-hamada-hn** [comment]
> 新しいディレクトリで abrg download から

下記を行った上でabrgを再実行しましたが、同様のエラーとなりました。

- 既存の `HOME/.abr-geocoder/database/` ディレクトリをリネーム
- 同名のディレクトリを作成
- `abrg download -c 422011` で上記ディレクトリ内にsqliteを作成

**Comment by maskatsum** [comment]
分かりました。ありがとうございます

**Comment by maskatsum** [comment]
![Untitled](https://github.com/user-attachments/assets/6f157185-4cca-4af9-9dfc-b60e66d643f5)
ちなみに WSL Settings の画面を確認させていただけますか？

**Comment by m-hamada-hn** [comment]
こちらでよろしいでしょうか。

![image](https://github.com/user-attachments/assets/adbf3bd2-c6c8-45fd-9941-6f7fd1b607e9)

**Comment by maskatsum** [comment]
ありがとうございます。うーん、十分そうですね...

**Comment by maskatsum** [comment]
@m-hamada-hn 試しになんですけど、プロセッサ数を`10` くらいにしてみても変わらないでしょうか。

**Comment by m-hamada-hn** [comment]
前回添付した画面でプロセッサ数を10に変更した上でWSLを起動、再実行しましたが変化ありませんでした。

**Comment by maskatsum** [comment]
そうですか。。。。ありがとうございます。

**Comment by maskatsum** [comment]
いろいろと手を尽くしてみましたが、まず同じスペックの環境が用意できないのと、再現ができないので、デバッグのしようがないです。
大変申し訳無いのですが、これ以上のサポートは難しいです。

p.s. 文字化けが発生する理由は解消しました

**Comment by m-hamada-hn** [comment]
> p.s. 文字化けが発生する理由は解消しました

`git pull` して確認してまいりましたが文字化け発生しておりました…。
（※まだ反映していない状態でしょうか。）

> これ以上のサポートは難しいです

承知致しました。
前述致しました通り、WSLではなくWindowsに構築した環境では
エラー、文字化け、共に発生していない状態ですので、こちらで引き続き利用させて頂きます。

長期間にわたりご尽力頂き、誠にありがとうございました。

**Comment by wf9a5m75** [comment]
> git pull して確認してまいりましたが文字化け発生しておりました…。
（※まだ反映していない状態でしょうか。）

git pull したあとに、npm run buildをされましたか？

```
# 古いバージョンをアンインストール
npm uninstall [-g] @digital-go-jp/abr-geocoder 


git pull

# ビルド
npm run build

# ローカルインストール
npm link 

# 使用する
npx abrg input.txt
```

**Comment by m-hamada-hn** [comment]
申し訳ありません。
標準出力等の挙動が変わっていたため`git pull` のみで良いと誤解しておりました。
ご提示頂いた手順により、文字化け、エラー共に発生しなくなったことを確認致しました。

**Comment by maskatsum** [comment]
お、良かったです。
では本件クローズさせていただきます
