### ISSUE TITLE
半角カタカナの「ｹ」が龍ケ崎市、金ヶ崎市、鎌ケ谷市などにヒットしない

### ISSUE THREAD

**Issue by koswatana** [digital-go-jp/abr-geocoder#166]
input | output | other | score | match_level | coordinate_level | lat | lon | lg_code | machiaza_id | rsdt_addr_flg | blk_id | rsdt_id | rsdt2_id | prc_id | pref | county | city | ward | oaza_cho | chome | koaza | blk_num | rsdt_num | rsdt_num2 | prc_num1 | prc_num2 | prc_num3 | pref_key | city_key | town_key | parcel_key | rsdtblk_key | rsdtdsp_key | spend_time
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
岩手県胆沢郡金ｹ崎町西根大谷120 金ケ崎小学校 | 岩手県胆沢郡金ｹ崎町西根大谷120 金ケ崎小学校 | 胆沢郡金ｹ崎町西根大谷120 金ケ崎小学校 | 1 | prefecture | prefecture | 39.703647 | 141.152592 | 030007 |   |   |   |   |   |   | 岩手県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859430 |   |   |   |   |   | 62.29
岩手県胆沢郡金ｹ崎町西根二ﾂ堤45-24 第一小学校 | 岩手県胆沢郡金ｹ崎町西根二ﾂ堤45-24 第一小学校 | 胆沢郡金ｹ崎町西根二ﾂ堤45-24 第一小学校 | 1 | prefecture | prefecture | 39.703647 | 141.152592 | 030007 |   |   |   |   |   |   | 岩手県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859430 |   |   |   |   |   | 62.28
岩手県胆沢郡金ｹ崎町三ヶ尻十三本塚16-2 三ケ尻小学校 | 岩手県胆沢郡金ｹ崎町三ヶ尻十三本塚16-2 三ケ尻小学校 | 胆沢郡金ｹ崎町三ヶ尻十三本塚16-2 三ケ尻小学校 | 1 | prefecture | prefecture | 39.703647 | 141.152592 | 030007 |   |   |   |   |   |   | 岩手県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859430 |   |   |   |   |   | 62.28
岩手県胆沢郡金ｹ崎町永沢堀切後下5 永岡小学校 | 岩手県胆沢郡金ｹ崎町永沢堀切後下5 永岡小学校 | 胆沢郡金ｹ崎町永沢堀切後下5 永岡小学校 | 1 | prefecture | prefecture | 39.703647 | 141.152592 | 030007 |   |   |   |   |   |   | 岩手県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859430 |   |   |   |   |   | 62.28
岩手県胆沢郡金ｹ崎町西根高谷野原23 西小学校 | 岩手県胆沢郡金ｹ崎町西根高谷野原23 西小学校 | 胆沢郡金ｹ崎町西根高谷野原23 西小学校 | 1 | prefecture | prefecture | 39.703647 | 141.152592 | 030007 |   |   |   |   |   |   | 岩手県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859430 |   |   |   |   |   | 62.28
茨城県龍ｹ崎市3316 龍ケ崎小学校 | 茨城県龍ｹ崎市3316 龍ケ崎小学校 | 龍ｹ崎市3316 龍ケ崎小学校 | 1 | prefecture | prefecture | 36.34145 | 140.446735 | 080004 |   |   |   |   |   |   | 茨城県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859597 |   |   |   |   |   | 48.38
茨城県龍ｹ崎市若柴町3135 馴柴小学校 | 茨城県龍ｹ崎市若柴町3135 馴柴小学校 | 龍ｹ崎市若柴町3135 馴柴小学校 | 1 | prefecture | prefecture | 36.34145 | 140.446735 | 080004 |   |   |   |   |   |   | 茨城県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859597 |   |   |   |   |   | 48.53
茨城県龍ｹ崎市藤ｹ丘1-22-4 八原小学校 | 茨城県龍ｹ崎市藤ｹ丘1-22-4 八原小学校 | 龍ｹ崎市藤ｹ丘1-22-4 八原小学校 | 1 | prefecture | prefecture | 36.34145 | 140.446735 | 080004 |   |   |   |   |   |   | 茨城県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859597 |   |   |   |   |   | 48.52
茨城県龍ｹ崎市大徳町4945 大宮小学校 | 茨城県龍ｹ崎市大徳町4945 大宮小学校 | 龍ｹ崎市大徳町4945 大宮小学校 | 1 | prefecture | prefecture | 36.34145 | 140.446735 | 080004 |   |   |   |   |   |   | 茨城県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859597 |   |   |   |   |   | 48.52
茨城県龍ｹ崎市川原代町3518 川原代小学校 | 茨城県龍ｹ崎市川原代町3518 川原代小学校 | 龍ｹ崎市川原代町3518 川原代小学校 | 1 | prefecture | prefecture | 36.34145 | 140.446735 | 080004 |   |   |   |   |   |   | 茨城県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859597 |   |   |   |   |   | 48.52
茨城県龍ｹ崎市8810 龍ケ崎西小学校 | 茨城県龍ｹ崎市8810 龍ケ崎西小学校 | 龍ｹ崎市8810 龍ケ崎西小学校 | 1 | prefecture | prefecture | 36.34145 | 140.446735 | 080004 |   |   |   |   |   |   | 茨城県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859597 |   |   |   |   |   | 48.52
茨城県龍ｹ崎市松葉2-9 松葉小学校 | 茨城県龍ｹ崎市松葉2-9 松葉小学校 | 龍ｹ崎市松葉2-9 松葉小学校 | 1 | prefecture | prefecture | 36.34145 | 140.446735 | 080004 |   |   |   |   |   |   | 茨城県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859597 |   |   |   |   |   | 48.52
茨城県龍ｹ崎市長山5-7-1 長山小学校 | 茨城県龍ｹ崎市長山5-7-1 長山小学校 | 龍ｹ崎市長山5-7-1 長山小学校 | 1 | prefecture | prefecture | 36.34145 | 140.446735 | 080004 |   |   |   |   |   |   | 茨城県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859597 |   |   |   |   |   | 48.52
茨城県龍ｹ崎市平台4-23-1 馴馬台小学校 | 茨城県龍ｹ崎市平台4-23-1 馴馬台小学校 | 龍ｹ崎市平台4-23-1 馴馬台小学校 | 1 | prefecture | prefecture | 36.34145 | 140.446735 | 080004 |   |   |   |   |   |   | 茨城県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859597 |   |   |   |   |   | 48.52
茨城県龍ｹ崎市久保台2-3 久保台小学校 | 茨城県龍ｹ崎市久保台2-3 久保台小学校 | 龍ｹ崎市久保台2-3 久保台小学校 | 1 | prefecture | prefecture | 36.34145 | 140.446735 | 080004 |   |   |   |   |   |   | 茨城県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859597 |   |   |   |   |   | 48.52
茨城県龍ｹ崎市城ﾉ内5-27 城ノ内小学校 | 茨城県龍ｹ崎市城ﾉ内5-27 城ノ内小学校 | 龍ｹ崎市城ﾉ内5-27 城ノ内小学校 | 1 | prefecture | prefecture | 36.34145 | 140.446735 | 080004 |   |   |   |   |   |   | 茨城県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859597 |   |   |   |   |   | 48.52
千葉県鎌ｹ谷市中央2-1-1 鎌ケ谷小学校 | 千葉県鎌ｹ谷市中央2-1-1 鎌ケ谷小学校 | 鎌ｹ谷市中央2-1-1 鎌ケ谷小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 0.56
千葉県鎌ｹ谷市中沢726-41 南部小学校 | 千葉県鎌ｹ谷市中沢726-41 南部小学校 | 鎌ｹ谷市中沢726-41 南部小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 0.72
千葉県鎌ｹ谷市粟野735 北部小学校 | 千葉県鎌ｹ谷市粟野735 北部小学校 | 鎌ｹ谷市粟野735 北部小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 0.71
千葉県鎌ｹ谷市鎌ｹ谷8-3-11 東部小学校 | 千葉県鎌ｹ谷市鎌ｹ谷8-3-11 東部小学校 | 鎌ｹ谷市鎌ｹ谷8-3-11 東部小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 0.71
千葉県鎌ｹ谷市初富110 西部小学校 | 千葉県鎌ｹ谷市初富110 西部小学校 | 鎌ｹ谷市初富110 西部小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 0.69
千葉県鎌ｹ谷市道野辺中央3-12-3 中部小学校 | 千葉県鎌ｹ谷市道野辺中央3-12-3 中部小学校 | 鎌ｹ谷市道野辺中央3-12-3 中部小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 0.69
千葉県鎌ｹ谷市東初富1-20-1 初富小学校 | 千葉県鎌ｹ谷市東初富1-20-1 初富小学校 | 鎌ｹ谷市東初富1-20-1 初富小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 0.69
千葉県鎌ｹ谷市東道野辺5-5-1 道野辺小学校 | 千葉県鎌ｹ谷市東道野辺5-5-1 道野辺小学校 | 鎌ｹ谷市東道野辺5-5-1 道野辺小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 0.60
千葉県鎌ｹ谷市南初富1-16-1 五本松小学校 | 千葉県鎌ｹ谷市南初富1-16-1 五本松小学校 | 鎌ｹ谷市南初富1-16-1 五本松小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 0.59
千葉県袖ｹ浦市坂戸市場1431 昭和小学校 | 千葉県袖ｹ浦市坂戸市場1431 昭和小学校 | 袖ｹ浦市坂戸市場1431 昭和小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 1.11
千葉県袖ｹ浦市長浦駅前6-1-4 長浦小学校 | 千葉県袖ｹ浦市長浦駅前6-1-4 長浦小学校 | 袖ｹ浦市長浦駅前6-1-4 長浦小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 1.15
千葉県袖ｹ浦市三ﾂ作761 根形小学校 | 千葉県袖ｹ浦市三ﾂ作761 根形小学校 | 袖ｹ浦市三ﾂ作761 根形小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 1.14
千葉県袖ｹ浦市横田2583 中川小学校 | 千葉県袖ｹ浦市横田2583 中川小学校 | 袖ｹ浦市横田2583 中川小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 1.14
千葉県袖ｹ浦市野里1503 平岡小学校 | 千葉県袖ｹ浦市野里1503 平岡小学校 | 袖ｹ浦市野里1503 平岡小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 1.11
千葉県袖ｹ浦市川原井470 平岡小学校幽谷分校 | 千葉県袖ｹ浦市川原井470 平岡小学校幽谷分校 | 袖ｹ浦市川原井470 平岡小学校幽谷分校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 1.14
千葉県袖ｹ浦市蔵波台4-19-1 蔵波小学校 | 千葉県袖ｹ浦市蔵波台4-19-1 蔵波小学校 | 袖ｹ浦市蔵波台4-19-1 蔵波小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 1.13
千葉県袖ｹ浦市奈良輪425-1 奈良輪小学校 | 千葉県袖ｹ浦市奈良輪425-1 奈良輪小学校 | 袖ｹ浦市奈良輪425-1 奈良輪小学校 | 1 | prefecture | prefecture | 35.604588 | 140.123184 | 120006 |   |   |   |   |   |   | 千葉県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859398 |   |   |   |   |   | 1.12
岐阜県不破郡関ｹ原町関ヶ原3132-3 関ケ原小学校 | 岐阜県不破郡関ｹ原町関ヶ原3132-3 関ケ原小学校 | 不破郡関ｹ原町関ヶ原3132-3 関ケ原小学校 | 1 | prefecture | prefecture | 35.391199 | 136.722168 | 210005 |   |   |   |   |   |   | 岐阜県 |   |   |   |   |   |   |   |   |   |   |   |   | 5859366 |   |   |   |   |   | 0.80

**Comment by maskatsum** [comment]
develop ブランチにて対応済み。
https://github.com/digital-go-jp/abr-geocoder/blob/f00a84591d1d157d55962306e310cf6bce1f0d48/e2e/test-data/issue166/expects.json
