### ISSUE TITLE
"other"のスペースが削除されてしまうケースがある

### ISSUE THREAD

**Issue by koswatana** [digital-go-jp/abr-geocoder#17]
例として`東京都千代田区紀尾井町1-999 ガーデンテラス`を入力した場合に
`-999`と`ガーデンテラス`の間の半角スペースが削除されてしまう

```
#  echo "東京都千代田区紀尾井町1-999 ガーデンテラス"|abr-geocoder normalize -f ndjson -|jq .
{
  "pref": "東京都",
  "city": "千代田区",
  "lg_code": "131016",
  "town": "紀尾井町",
  "town_id": "0056000",
  "other": "-999ガーデンテラス",
  "lat": 35.679921,
  "lon": 139.737183,
  "level": 7,
  "blk": "1",
  "blk_id": "001"
}
```

**Comment by wf9a5m75** [comment]
## before
![Screenshot 2023-07-10 at 12 37 45 AM](https://github.com/digital-go-jp/abr-geocoder/assets/167831/823911ee-f9ff-4162-af7a-e64274a3d510)

## after

![Screenshot 2023-07-10 at 12 38 19 AM](https://github.com/digital-go-jp/abr-geocoder/assets/167831/6531363e-4792-49c2-9c66-33a7d3d602a1)
