### ISSUE TITLE
リファクタリング

### ISSUE THREAD

**Issue by wf9a5m75** [digital-go-jp/abr-geocoder#24]
# 概要

- コード全体的に可読性が悪く、メンテナンスコストが高い。
- 全体的なコードのリファクタリングが必要。
- モジュールとして読み込めるようにする

# 説明

- [x] ESLint を導入して、コード全体の書式を統一する (#32 )
- [x] DI を導入して、各コードの依存性を低くし、モジュールやクラスごとの凝縮度を高める
- [x] 全角文字を使った正規表現パターンが散見されるが、バグを起こしやすいので、~`\uXXXX` 形式に変換する~ 可能な限り定数値化する
- [x] i18nを導入して、メッセージを日本語/英語切り替えできるようにする
- [x] DBカラム名に日本語が使用されているので、英語に全部置換する

**Comment by maskatsum** [comment]
> i18nを導入して、メッセージを日本語/英語切り替えできるようにする

仕組みは導入完了。

`enum MESSAGE` (https://github.com/digital-go-jp/abr-geocoder/blob/458ee886020cf5808e419cd4918181ae7831069a/src/cli/usecase/strResource/locales/index.ts) にIDを追加して、[日本語ファイル](https://github.com/digital-go-jp/abr-geocoder/blob/458ee886020cf5808e419cd4918181ae7831069a/src/cli/usecase/strResource/locales/ja.ts)と[英語ファイル](https://github.com/digital-go-jp/abr-geocoder/blob/458ee886020cf5808e419cd4918181ae7831069a/src/cli/usecase/strResource/locales/ja.ts) にメッセージを追加。

**Comment by maskatsum** [comment]
> DI を導入して、各コードの依存性を低くし、モジュールやクラスごとの凝縮度を高める

コンテナの定義は、[config/setupContainer.ts](
https://github.com/digital-go-jp/abr-geocoder/blob/458ee886020cf5808e419cd4918181ae7831069a/src/cli/config/setupContainer.ts)

**Comment by maskatsum** [comment]
> DBカラム名に日本語が使用されているので、英語に全部置換する

このWiki に従う
https://github.com/digital-go-jp/abr-geocoder/wiki/%E6%97%A5%E8%8B%B1%E5%AF%BE%E5%BF%9C%E8%A1%A8

**Comment by maskatsum** [comment]
> 全角文字を使った正規表現パターンが散見されるが、バグを起こしやすいので、\uXXXX 形式に変換する

外部ファイル化する方向で検討
https://github.com/digital-go-jp/abr-geocoder/issues/37

**Comment by maskatsum** [comment]
> DBカラム名に日本語が使用されているので、英語に全部置換する

https://github.com/digital-go-jp/abr-geocoder/pull/36/commits/d663c400dafbd2e648784d60c85146e6e9fc8619 で対応

**Comment by maskatsum** [comment]
Note: [クリーンアーキテクチャ](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html) に基づいたディレクトリ構成でリファクタリング中。

**Comment by maskatsum** [comment]
元のコードがあまりにも良くなかったので、全て書き直しました。
