### ISSUE TITLE
`normalize` サブコマンドを削除する

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#29]
# 概要

`normalize` サブコマンドが冗長なので、削除する。（そもそもgeocoderなので、geocodingすることが前提である。敢えてサブコマンドで指定する必要性がない）

## 関連するチケット

https://github.com/digital-go-jp/abr-geocoder/issues/10#issuecomment-1600304389

**Comment by koswatana** [comment]
以下のように実行できるように改修
```
echo "(住所)" | abrg -
```

**Comment by maskatsum** [comment]
https://github.com/digital-go-jp/abr-geocoder/pull/36/commits/458ee886020cf5808e419cd4918181ae7831069a で `normalize` コマンドを削除しました。

```
echo "(住所)" | abrg 
```
で使えるようになりますが、まだコマンド本体を実装していないので、もう少しお待ち下さい

**Comment by koswatana** [comment]
@maskatsum 
> ```
> echo "(住所)" | abrg 
> ```
> 
> で使えるようになりますが、まだコマンド本体を実装していないので、もう少しお待ち下さい
標準入力のハイフンもなくす予定でしょうか？

**Comment by maskatsum** [comment]
いえ、それは残します。（どちらでも対応できます）

**Comment by maskatsum** [comment]
v1.1 にて実装しました。
https://github.com/digital-go-jp/abr-geocoder/blob/3018aa8abb51daef89fbf8062859561a3fcb494d/spec/execution-test.spec.mjs
