### ISSUE TITLE
旧字・新字、ゆらぎのリストを外部ファイル化する

### ISSUE THREAD

**Issue by koswatana** [digital-go-jp/abr-geocoder#37]
`src/engine/lib/dict.ts`の旧字・新字、ゆらぎのリストがハードコーディングされているので、yaml等外部ファイル化する

https://github.com/digital-go-jp/abr-geocoder/blob/develop/src/engine/lib/dict.ts#L1-L9
https://github.com/digital-go-jp/abr-geocoder/blob/develop/src/engine/lib/dict.ts#L35-L60

**Comment by masanork** [comment]
ありがとうございます。書き込もうとしたところ、既にご対応されていましたね。遅くなってしまい失礼いたしました

**Comment by maskatsum** [comment]
外部ファイルへの対応に時間がかかりそうだったので、v1.1では、`src/settings` にまとめました。
https://github.com/digital-go-jp/abr-geocoder/tree/features/issue_24/src/settings

**Comment by maskatsum** [comment]
v2.0.0では、Clean Architecture に基づいて、`src/usecases/geocode/services/jis-kanji.ts` に格納しました。
変更する必要があれば、PRを送ってください

https://github.com/digital-go-jp/abr-geocoder/blob/c367c81/src/usecases/geocode/services/jis-kanji.ts
