### ISSUE TITLE
丁目が存在しない住所に対する誤解に基づく表記ゆらぎへの対応

### ISSUE THREAD

**Issue by masanork** [digital-go-jp/abr-geocoder#38]
例えばサンプルでも使われている「東京都千代田区紀尾井町1-3」について、紀尾井町そのものが町字であることを正しく理解して「東京都千代田区紀尾井町1番地3号」と記載した場合は正しくジオコーディングされるが、誤解して「東京都千代田区紀尾井町1丁目3番地」と書くと正しく認識できません。町字そのものが丁目までを示す紀尾井町・番町といった町字について、番地を丁目と誤解して誤記した場合であっても、正しくジオコーディングできないでしょうか。

**Comment by maskatsum** [comment]
今日、この辺のコードをリファクタリングしていました。
端的な結論から述べると、現時点では難しいです。

現時点のコードでは正規表現パターン駆使して解析をしているので、あまり自由度が効きません。

自分の中では別のアルゴリズムのアイディアはあり、それならできそうな気はしますが、まずはリファクタリング作業優先で進めたいと思います。

**Comment by maskatsum** [comment]
記録のため、v1.1.1 で試してみました。

### (サンプル) 東京都千代田区紀尾井町1-3 で与えた場合
```
$> echo "東京都千代田区紀尾井町1-3" | npx abrg -

[{"query":{"input":"東京都千代田区紀尾井町1-3"},"result":{"prefecture":"東京都","match_level":8,"city":"千代田区","town":"紀尾井町","town_id":"0056000","lg_code":"131016","other":"","lat":35.679107172,"lon":139.736394597,"block":"1","block_id":"001","addr1":"3","addr1_id":"003","addr2":"","addr2_id":""}}]
```

### (正しい住所) 東京都千代田区紀尾井町1番地3号 で与えた場合
```
 $> echo "東京都千代田区紀尾井町1番地3号" | npx abrg -

[{"query":{"input":"東京都千代田区紀尾井町1番地3号"},"result":{"prefecture":"東京都","match_level":8,"city":"千代田区","town":"紀尾井町","town_id":"0056000","lg_code":"131016","other":"","lat":35.679107172,"lon":139.736394597,"block":"1","block_id":"001","addr1":"3","addr1_id":"003","addr2":"","addr2_id":""}}]
```


### (不正確な住所) 東京都千代田区紀尾井町1丁目3番地 で与えた場合
```
$> echo "東京都千代田区紀尾井町1丁目3番地" | npx abrg -

[{"query":{"input":"東京都千代田区紀尾井町1丁目3番地"},"result":{"prefecture":"東京都","match_level":3,"city":"千代田区","town":"紀尾井町","town_id":"0056000","lg_code":"131016","other":"丁目3","lat":35.681411,"lon":139.73495}}]
```

**Comment by maskatsum** [comment]
(単純に ◯番地◯丁目◯番地を ◯-◯-◯の省略形にしてしまえば解決する気がするけど、それによって正しくジオコードできなくなるケースがどの程度あるかは、現時点で読めない)

**Comment by koswatana** [comment]
v2-rcでtargetオプションを追加

```
# echo "東京都千代田区紀尾井町1丁目3番地"|abrg - --target residential|jq .
[
  {
    "query": {
      "input": "東京都千代田区紀尾井町1丁目3番地"
    },
    "result": {
      "output": "東京都千代田区紀尾井町1-3",
      "score": 0.77,
      "other": null,
      "match_level": "residential_detail",
      "lg_code": "131016",
      "pref": "東京都",
      "county": null,
      "city": "千代田区",
      "ward": null,
      "machiaza_id": "0056000",
      "oaza_cho": "紀尾井町",
      "chome": null,
      "koaza": null,
      "blk_num": "1",
      "blk_id": "001",
      "rsdt_num": 3,
      "rsdt_id": "003",
      "rsdt_num2": null,
      "rsdt2_id": null,
      "rsdt_addr_flg": 1,
      "prc_num1": null,
      "prc_num2": null,
      "prc_num3": null,
      "prc_id": null,
      "lat": 35.679107172,
      "lon": 139.736394597,
      "coordinate_level": "residential_detail"
    }
  }
]
```

**Comment by koswatana** [comment]
現行実装（db_version 3.0.0）での挙動と、対応可否の調査結果を事実として記録します。

### 現状の挙動（`abrg match`, 全国キャッシュ）

`紀尾井町` は ABR 上 `has_chome=false`（丁目を持たず rsdtdsp を直下に持つ町字）です。

| 入力 | matched_address | match_level |
|---|---|---|
| 東京都千代田区紀尾井町1-3 | 東京都千代田区紀尾井町1-3 | rsdtdsp_rsdt |
| 東京都千代田区紀尾井町1番地3号 | 東京都千代田区紀尾井町1-3 | rsdtdsp_rsdt |
| 東京都千代田区紀尾井町1丁目3番地 | 東京都千代田区紀尾井町 | machiaza |
| 東京都千代田区紀尾井町1丁目3号 | 東京都千代田区紀尾井町 | machiaza |

`1-3` / `1番地3号`（`1` を街区として解釈する形）は住居表示まで到達しますが、本 issue の「丁目を持たない町字に `N丁目M` と誤記した」形は machiaza 止まりで、この点は未対応のままです。

### 対応可否の調査

「丁目なし町字に丁目マーカーが付いた場合、丁目を街区番号として解釈し直す（`1丁目3`→`1-3`）」という補正を two-stage 検索層に入れて検証しましたが、**効きませんでした**。

原因は、`N丁目` が丁目マーカー化された時点で基底町字への完全一致に失敗し、**曖昧マッチ（Levenshtein）にフォールバックした時点で住居表示・地番の 2 段マッチがまとめてスキップされる**ため（この skip 挙動は #246 に整理）です。two-stage 層の補正はこのスキップにより実行されません。

有効な対応には、基底町字の検出層（`detectMachiaza`）側で「丁目マーカー付きで完全一致しない場合に丁目を街区へ降格して再検出する」変更が必要です。ただし `has_chome=false` かつ rsdtdsp/parcel を持つ町字は約 40 万件と母数が大きく、保守的な machiaza 応答を確信度の高い住居表示応答へ変える際の誤検出（偽陽性）の波及を、実住所コーパスでの before/after 差分で定量化する必要があります。

以上より、本件は小規模・低リスクな修正では対応できず、検出コアの変更＋影響測定を要する既知の制限として整理します。対応を進める場合は再オープンしてください。
