### ISSUE TITLE
Macでのインストール時に better-sqlite3 コマンドの実行に失敗

### ISSUE THREAD

**Issue by masanork** [digital-go-jp/abr-geocoder#40]
macOS環境において
brew install nodejs
brew install yarn のあと、
yarn global add digital-go-jp/abr-geocoder
と実行しても、better-sqlite3: Command failed. と出て失敗してしまいました。
README.md中でMacでの利用では、
npm install -g node-gyp が必要と明記した方がいいかも知れません。

**Comment by koswatana** [comment]
インストール方法が変更になる予定
https://github.com/digital-go-jp/abr-geocoder/issues/19
https://github.com/digital-go-jp/abr-geocoder/tree/develop
https://github.com/digital-go-jp/abr-geocoder/issues/28

**Comment by maskatsum** [comment]
@masanork さん、情報ありがとうございます。
インストール方法は変更になりますが、（当面は）引き続き better-sqlite3 を使うので、バージョンアップ前に検証したいと思います。

**Comment by maskatsum** [comment]
v1.1 に該当する症状が再現しませんでした。ただたしかに一番最初にインストールしたときに、同様のエラーを見たような記憶があるので、発生するかもしれません。引き続き情報を求めるため、issue を openにしておきます。

**Comment by maskatsum** [comment]
どうやら、`yarn` や `pnpm` などを使うと、発生しやすいようです。
これらのコマンドは、なるべくキャッシュを使用するためです。

v2.0.0 では、アドバイスを頂いた通り、`node-gyp` をインストールするようにしました。
