### ISSUE TITLE
出力フォーマットで正規化後住所文字列のみ出力に対応

### ISSUE THREAD

**Issue by koswatana** [digital-go-jp/abr-geocoder#42]
## イメージ
- オプション名は要検討
- 緯度、経度は不要？
  - 不要
```
# echo "東京都千代田区霞ヶ関３丁目５番２号"|abrg -format normalizetext -
東京都千代田区霞が関三丁目5-2
```

https://github.com/digital-go-jp/abr-geocoder/issues/30

**Comment by wf9a5m75** [comment]
えっと、正規化された住所が欲しい、ということでしょうか？

**Comment by koswatana** [comment]
はい、そうです
ジオコーディングなしで、住所文字列の正規化のみを行うという需要があります

**Comment by maskatsum** [comment]
v1 のアルゴリズムだと、住所の正規化とともに緯度経度を取得するようになっていて、仮に緯度経度を取得しなくても処理速度は変わらないし、実装が複雑になるので、この機能は実装をしませんでした。
取得後に`jq` などで処理をしてくだささい。

**Comment by maskatsum** [comment]
v1.1 には実装しませんでした。v1.2 とかで検討。

**Comment by koswatana** [comment]
https://github.com/digital-go-jp/abr-geocoder/issues/41#issuecomment-1677330450
inputのテキストも合わせて出力

1行の場合はこんな感じ
```
# echo "東京都千代田区霞ヶ関３丁目５番２号"|abrg -format normalizetext -
"東京都千代田区霞ヶ関３丁目５番２号","東京都千代田区霞が関三丁目5-2"
```

複数行の場合は検討

**Comment by maskatsum** [comment]
実装しましたー

**Comment by koswatana** [comment]
@maskatsum 
想定はこれ専用のformatオプションを出力することを想定していました
ただjsonに入れるのもありではありますね

**Comment by koswatana** [comment]
本issueは、以下のissueのような

https://github.com/digital-go-jp/abr-geocoder/issues/78
> ■達成したいこと
> 丁目以降の数字（丁目・番地）の表記が揺れている2つの住所があり、abrg コマンドを使うことによって、同一の住所と判定したい（＝表記ゆれの正規化の目的で abrg を使いたい）ため、どのように実現可能かを検証したい。
をという名寄せのユースケースを達成するのが目的

v1.2.0でoutputに対応したが意図しない正規化とフィールド名が分かりづらいため修正を行う
- 意図しない正規化は以下のissueで対応
  - https://github.com/digital-go-jp/abr-geocoder/issues/66 
- フィールド名は`output`を`formatted_address`に修正

また、名寄せのユースケースでは座標値等は不要なためオプションに`formatted`を追加し、csvと同じ仕様(複数行処理の場合は1回のみヘッダーを表示)で"input","formatted_address"のフィールドのみ出力

```
# echo "東京都千代田区霞ヶ関３丁目５番２号"|abrg -format formatted -
"input","formatted_address"
"東京都千代田区霞ヶ関３丁目５番２号","東京都千代田区霞が関三丁目5-2"
```

**Comment by koswatana** [comment]
```
root@56a50b3a9139:/workspaces/abr-geocoder# echo "東京都千代田区紀尾井町１番３号 デジタルビル９９９"|npx ts-node ./src/cli/cli.ts - -f normalize
input,normalized_address,match_level
"東京都千代田区紀尾井町１番３号 デジタルビル９９９","東京都千代田区紀尾井町1-3 デジタルビル999",8
```

**Comment by koswatana** [comment]
対応方針
- `output`の名称変更はせずv2で検討を行い対応する
https://github.com/digital-go-jp/abr-geocoder/issues/91

- formatオプション名
  - `normalize`
  
 - 出力項目
   - `input`, `output`, `match_level`
     - マッチングレベルによって`output`が変わる(otherの前に半角スペースが入る)ので`match_level`追加
