### ISSUE TITLE
番地・号の区切りハイフンの揺らぎ対応検証

### ISSUE THREAD

**Issue by koswatana** [digital-go-jp/abr-geocoder#44]
`-`(ハイフン)に似ていてOCRや手入力等で揺らぐ可能性のある文字について検証

### 揺らぐ可能性のある文字

`－`	全角ハイフンマイナス
`-`	半角ハイフンマイナス
`−`	全角マイナス
`‐`	全角ハイフン
`‒`	フィギュアーダッシュ
`–`	二分ダッシュ
`—`	全角ダッシュ
`─`	罫線
`━`	罫線（太）
`一`	いち
`―`	ホリゾンタルバー
`ー`	全角長音
`ｰ`	半角長音

### 検証
- v1.0.0で検証
```
root@5ed95e519b77:/# cat /tmp/test.txt 
東京都千代田区紀尾井町1-3 半角ハイフン
東京都千代田区紀尾井町1－3 全角ハイフンマイナス
東京都千代田区紀尾井町1-3 半角ハイフンマイナス
東京都千代田区紀尾井町1−3 全角マイナス
東京都千代田区紀尾井町1‒3 フィギュアーダッシュ
東京都千代田区紀尾井町1– 3 二分ダッシュ
東京都千代田区紀尾井町1—3 全角ダッシュ
東京都千代田区紀尾井町1─3 罫線
東京都千代田区紀尾井町1━3 罫線（太）
東京都千代田区紀尾井町1一3 漢数字いち
東京都千代田区紀尾井町1―3 ホリゾンタルバー
東京都千代田区紀尾井町1ー3 全角長音
東京都千代田区紀尾井町1ｰ3 半角長音
root@5ed95e519b77:/# abr-geocoder normalize -f ndjson /tmp/test.txt|jq .other
"半角ハイフン"
"全角ハイフンマイナス"
"半角ハイフンマイナス"
"全角マイナス"
"フィギュアーダッシュ"
"- 3 二分ダッシュ"
"全角ダッシュ"
"罫線"
"罫線（太）"
"一3 漢数字いち"
"ホリゾンタルバー"
"全角長音"
"半角長音"
```

### 結果
「二分ダッシュ」と「漢数字いち」以外は対応できている

**Comment by koswatana** [comment]
実装箇所
https://github.com/digital-go-jp/abr-geocoder/blob/main/src/engine/normalize.ts#L440

**Comment by maskatsum** [comment]
調べていただきありがとうございます。追加しますね。

> return kan2num(match).replace(/[-－﹣−‐⁃‑‒–—﹘―⎯⏤ーｰ─━]/g, '-') 

このコード、可読性悪いなー。どれがどの記号だか全く分からない...

**Comment by koswatana** [comment]
結果としては「漢数字のいち」と「二分ダッシュ」以外は対応できている
「漢数字のいち」が番地・号の区切り文字として使われてしまっている場合、`紀尾井町1一3`のようなケースであれば対応可能かもしれないが、`紀尾井町一一三` のような場合は対応が難しそう
とりあえず「二分ダッシュを対応」する

**Comment by maskatsum** [comment]
v1.1 で対応しました

**Comment by koswatana** [comment]
現行実装（v3, db_version 3.0.0）で報告のダッシュ揺らぎを再検証しました。事実として記録します。

`abrg match` に本 issue の各文字を流した結果、報告時に未対応とされた2件のうち **二分ダッシュ（–, U+2013）は対応済み**になっています。

| 入力 | matched_address | match_level |
|---|---|---|
| 東京都千代田区紀尾井町1‒3（フィギュアダッシュ）| 東京都千代田区紀尾井町1-3 | rsdtdsp_rsdt |
| 東京都千代田区紀尾井町1–3（二分ダッシュ）| 東京都千代田区紀尾井町1-3 | rsdtdsp_rsdt |
| 東京都千代田区紀尾井町1—3（全角ダッシュ）| 東京都千代田区紀尾井町1-3 | rsdtdsp_rsdt |
| 東京都千代田区紀尾井町1―3（ホリゾンタルバー）| 東京都千代田区紀尾井町1-3 | rsdtdsp_rsdt |
| 東京都千代田区紀尾井町1ー3（全角長音）| 東京都千代田区紀尾井町1-3 | rsdtdsp_rsdt |
| 東京都千代田区紀尾井町1一3（漢数字いち）| 東京都千代田区紀尾井町1 | rsdtdsp_blk（`一3` 未マッチ）|

残るのは **漢数字「一」** のみです。ただし `一` は実在の漢数字（`一番町`・`一の…` 等の地名や数値に現れる）であり、区切り記号として一律にハイフン化すると地名・数値を誤って壊すリスクが高いため、他のダッシュ類とは分けて扱うのが妥当と考えられます。
