### ISSUE TITLE
devcontanerの導入

### ISSUE THREAD

**Issue by koswatana** [digital-go-jp/abr-geocoder#45]
VS Code + Dev Containersで開発ができるようにする
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

**Comment by koswatana** [comment]
#46

**Comment by koswatana** [comment]
#46

**Comment by maskatsum** [comment]
https://github.com/digital-go-jp/abr-geocoder/pull/49/commits/959d746e74457e6b6e4cd2c7b03e824774b6df4e

**Comment by maskatsum** [comment]
v1.1 に取り込まれました。
