### ISSUE TITLE
sqliteのmetadataにダウンロード時のversion情報を管理する

### ISSUE THREAD

**Issue by koswatana** [digital-go-jp/abr-geocoder#47]
ジオコーダーのバージョンアップでテーブル構造が変わる可能性があるので、sqliteのmetadataテーブルにダウンロード時のバージョン情報を管理して、実行時とDBのバージョンが異なる場合は更新できる可能性を示す

### 現状のmetadataテーブル
key | value
-- | --
last_modified | 2023-06-14T20:03:14
original_file_url | https://catalog.registries.digital.go.jp/rsc/address/address_all.csv.zip

**Comment by maskatsum** [comment]
v1.0 と v1.1 だとDBテーブルに互換性がないです。ただこの機能も入れてないです（似たような機能はv1.1 に実装しました)

**Comment by maskatsum** [comment]
sqlite に metadata を入れる方法は、v2.0.0 では採用しませんでした。
