### ISSUE TITLE
github workflowの改善

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#55]
# 概要

NPMリリースのステップを改善するため、github workflow を改善する。tag で `1.x` が付いたら npmでのリリースのためのworkflow を動作させる。テスト用に手動でも起動できるようにする。この場合は dry-run で実行する

**Comment by koswatana** [comment]
https://github.com/digital-go-jp/abr-geocoder/pull/4

**Comment by maskatsum** [comment]
このようにしました。以前考えていた、自動でバージョン番号のインクリメントは入れていませんので、develop -> mainブランチへのPR作成時にpackage.json を書き換えてください。

一旦、これで運用してみて、都合が悪ければ修正していきましょう。

### 他のブランチ → developブランチへのPR

- lint, テスト などのチェックが行われる

### develop → mainブランチへのPR

- npm publish --dry-run が実行される
- https://github.com/digital-go-jp/abr-geocoder/releases にnpmリリースされる成果物が生成される

### develop -> mainブランチにマージされたとき

- npm publish される
