### ISSUE TITLE
build は普通は含めない

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#6]
TypeScriptでコードを書く場合、通常は生成物である `build (dest, dst, etc)` はリポジトリに含めないですねー。昨今だと Github Actionなどの CI/CDで、自動的に npm publish するときにビルドします。いつビルドされたものか分からないからですね。

でも、Github Actionsの使用が制限されている場合もあるので、まぁそのときは仕方ないかなと。

**Comment by koswatana** [comment]
- buildの削除
- .gitignoreに追記

**Comment by maskatsum** [comment]
workflow の PRも後で作ります

**Comment by maskatsum** [comment]
PR #20 で対応完了
