### ISSUE TITLE
仕様で意図しない正規化がされる

### ISSUE THREAD

**Issue by koswatana** [digital-go-jp/abr-geocoder#66]
関連Issues
- [x] https://github.com/digital-go-jp/abr-geocoder/issues/86
- [x] https://github.com/digital-go-jp/abr-geocoder/issues/88
- [x] https://github.com/digital-go-jp/abr-geocoder/issues/89
- [x] https://github.com/digital-go-jp/abr-geocoder/issues/90

---

> [!NOTE] 
> 前提としてアドレス・ベース・レジストリがまだ通り名には対応をしていないのでジオコーダーも未対応
> 通り名が原因かは不明
> 正規化が正しくされない(`other`に正しく入らない)のが問題

- ビル名の後に５号という文字が含まれると5丁目になってしまう

```
# echo "京都府京都市中京区衣棚通姉小路下る突抜町１３２番地"|abrg -
[{"query":{"input":"京都府京都市中京区衣棚通姉小路下る突抜町１３２番地"},"result":{"prefecture":"京都府","match_level":3,"city":"京都市中京区","town":"突抜町","town_id":"0253000","lg_code":"261041","other":"132","lat":35.009372,"lon":135.75729800000002}}]
# echo "京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル"|abrg -
[{"query":{"input":"京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル"},"result":{"prefecture":"京都府","match_level":3,"city":"京都市中京区","town":"突抜町","town_id":"0253000","lg_code":"261041","other":"132 デジタルビル","lat":35.009372,"lon":135.75729800000002}}]
#  echo "京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル ５号"|abrg -
[{"query":{"input":"京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル ５号"},"result":{"prefecture":"京都府","match_level":3,"city":"京都市中京区","town":"五丁目","town_id":"0000005","lg_code":"261041","other":"","lat":35.015582,"lon":135.763968}}]
```

- 1号~7号で試してみる
  - 四丁目~六丁目で再現する
  - 町字IDから見るに以下にマッチングしていそう
 

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head></head><body>
261041 | 0000004 | 2 | 京都府 | キョウトフ | Kyoto |   |   |   | 京都市 | キョウトシ | Kyoto-shi | 中京区 | ナカギョウク | Nakagyo-ku |   |   |   | 四丁目 | ４チョウメ | 4 |   |   |   | 0 | 0 | 0 |   | 0 | 0 | 0 | 0 | 1947-04-17 |   | 0 | 6040974 |   | 135.764047 | 35.016866
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
261041 | 0000005 | 2 | 京都府 | キョウトフ | Kyoto |   |   |   | 京都市 | キョウトシ | Kyoto-shi | 中京区 | ナカギョウク | Nakagyo-ku |   |   |   | 五丁目 | ５チョウメ | 5 |   |   |   | 0 | 0 | 0 |   | 0 | 0 | 0 | 0 | 1947-04-17 |   | 0 | 6040973 |   | 135.763968 | 35.015582
261041 | 0000006 | 2 | 京都府 | キョウトフ | Kyoto |   |   |   | 京都市 | キョウトシ | Kyoto-shi | 中京区 | ナカギョウク | Nakagyo-ku |   |   |   | 六丁目 | ６チョウメ | 6 |   |   |   | 0 | 0 | 0 |   | 0 | 0 | 0 | 0 | 1947-04-17 |   | 0 | 6040965 |   | 135.763985 | 35.014288

</body></html>

```
# echo "京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　１号"|abrg -
[{"query":{"input":"京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　１号"},"result":{"prefecture":"京都府","match_level":3,"city":"京都市中京区","town":"突抜町","town_id":"0253000","lg_code":"261041","other":"132 デジタルビル 1号","lat":35.009372,"lon":135.75729800000002}}]
# echo "京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　２号"|abrg -
[{"query":{"input":"京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　２号"},"result":{"prefecture":"京都府","match_level":3,"city":"京都市中京区","town":"突抜町","town_id":"0253000","lg_code":"261041","other":"132 デジタルビル 2号","lat":35.009372,"lon":135.75729800000002}}]
# echo "京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　３号"|abrg -
[{"query":{"input":"京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　３号"},"result":{"prefecture":"京都府","match_level":3,"city":"京都市中京区","town":"突抜町","town_id":"0253000","lg_code":"261041","other":"132 デジタルビル 3号","lat":35.009372,"lon":135.75729800000002}}]
# echo "京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　４号"|abrg -
[{"query":{"input":"京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　４号"},"result":{"prefecture":"京都府","match_level":3,"city":"京都市中京区","town":"四丁目","town_id":"0000004","lg_code":"261041","other":"","lat":35.016866,"lon":135.764047}}]
# echo "京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　５号"|abrg -
[{"query":{"input":"京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　５号"},"result":{"prefecture":"京都府","match_level":3,"city":"京都市中京区","town":"五丁目","town_id":"0000005","lg_code":"261041","other":"","lat":35.015582,"lon":135.763968}}]
# echo "京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　６号"|abrg -
[{"query":{"input":"京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　６号"},"result":{"prefecture":"京都府","match_level":3,"city":"京都市中京区","town":"六丁目","town_id":"0000006","lg_code":"261041","other":"","lat":35.014288,"lon":135.763985}}]
# echo "京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　７号"|abrg -
[{"query":{"input":"京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　７号"},"result":{"prefecture":"京都府","match_level":3,"city":"京都市中京区","town":"突抜町","town_id":"0253000","lg_code":"261041","other":"132 デジタルビル 7号","lat":35.009372,"lon":135.75729800000002}}]
```

- 最後に`号`とついた場合に意図しない正規化が行われる ⇒ #89 

```
# echo "京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　９９９５号"|abrg -
[{"query":{"input":"京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　９９９５号"},"result":{"prefecture":"京都府","match_level":3,"city":"京都市中京区","town":"五丁目","town_id":"0000005","lg_code":"261041","other":"","lat":35.015582,"lon":135.763968}}]
# echo "京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　９９９５"|abrg -
[{"query":{"input":"京都府京都市中京区衣棚通姉小路下る突抜町１３２番地　デジタルビル　９９９５"},"result":{"prefecture":"京都府","match_level":3,"city":"京都市中京区","town":"突抜町","town_id":"0253000","lg_code":"261041","other":"132 デジタルビル 9995","lat":35.009372,"lon":135.75729800000002}}]
```

- 通り名に対応できていない現状ではcityより下の階層はotherに入る想定 ⇒ #88 

```
# echo "京都市中京区寺町通御池上る上本能寺前町４８８番地"|abrg -
[{"query":{"input":"京都市中京区寺町通御池上る上本能寺前町４８８番地"},"result":{"prefecture":"京都府","match_level":2,"city":"京都市","other":"中京区寺町通御池上る上本能寺前町488番地","lat":null,"lon":null}}]
# echo "京都市中京区寺町通御池上る上本能寺前町４８８番地　デジタルビル"|abrg -
[{"query":{"input":"京都市中京区寺町通御池上る上本能寺前町４８８番地　デジタルビル"},"result":{"prefecture":"京都府","match_level":2,"city":"京都市","other":"中京区寺町通御池上る上本能寺前町488番地 デジタルビル","lat":null,"lon":null}}]
# echo "京都市中京区寺町通御池上る上本能寺前町４８８番地　デジタルビル　９９９号"|abrg -
[{"query":{"input":"京都市中京区寺町通御池上る上本能寺前町４８８番地　デジタルビル　９９９号"},"result":{"prefecture":"京都府","match_level":2,"city":"京都市","other":"中京区寺町通御池上る上本能寺前町488番地 デジタルビル 999号","lat":null,"lon":null}}]
# echo "京都府京都市中京区衣棚通姉小路下る突抜町１３２番地"|abrg -
[{"query":{"input":"京都府京都市中京区衣棚通姉小路下る突抜町１３２番地"},"result":{"prefecture":"京都府","match_level":3,"city":"京都市中京区","town":"突抜町","town_id":"0253000","lg_code":"261041","other":"132","lat":35.009372,"lon":135.75729800000002}}]
```

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head></head><body>
261041 | 0424000 | 1 | 京都府 | キョウトフ | Kyoto |   |   |   | 京都市 | キョウトシ | Kyoto-shi | 中京区 | ナカギョウク | Nakagyo-ku | 本能寺町 | ホンノウジチョウ | Honnojicho |   |   |   |   |   |   | 0 | 0 | 0 |   | 0 | 0 | 0 | 1 | 1947-04-17 |   | 0 | 6048243 |   | 135.75444 | 35.007288
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

</body></html>

**Comment by koswatana** [comment]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head></head><body>
012157 | 0000006 | 2 | 北海道 | ホッカイドウ | Hokkaido |   |   |   | 美唄市 | ビバイシ | Bibai-shi |   |   |   |   |   |   | 六丁目 | ６チョウメ | 6 |   |   |   | 0 | 0 | 0 |   | 0 | 0 | 0 | 0 | 1947-04-17 |   | 0 |   |   | 141.8658 | 43.306258
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
072087 | 0000001 | 2 | 福島県 | フクシマケン | Fukushima |   |   |   | 喜多方市 | キタカタシ | Kitakata-shi |   |   |   |   |   |   | 一丁目 | １チョウメ | 1 |   |   |   | 0 | 0 | 0 |   | 0 | 0 | 0 | 1 | 1947-04-17 |   | 0 | 9660819 |   | 139.872673 | 37.655616
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
</body></html>

似たようなデータで試すが再現しない

```
# echo "北海道美唄市9999 デジタルビル 6号"|abrg -
[{"query":{"input":"北海道美唄市9999 デジタルビル 6号"},"result":{"prefecture":"北海道","match_level":2,"city":"美唄市","other":"9999 デジタルビル 6号","lat":null,"lon":null}}]
# echo "福島県喜多方市9999番地　デジタルビル　９９９１号"|abrg -
[{"query":{"input":"福島県喜多方市9999番地　デジタルビル　９９９１号"},"result":{"prefecture":"福島県","match_level":2,"city":"喜多方市","other":"9999番地 デジタルビル 9991号","lat":null,"lon":null}}]
```

**Comment by koswatana** [comment]
331031 | 0000002 | 2 | 岡山県 | オカヤマケン | Okayama |   |   |   | 岡山市 | オカヤマシ | Okayama-shi | 東区 | ヒガシク | Higashi-ku |   |   |   | 二丁目 | ２チョウメ | 2 |   |   |   | 0 | 0 | 0 |   | 0 | 0 | 0 | 0 | 1947-04-17 |   | 0 |   |   | 134.032833 | 34.617378
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

政令市区があるデータで試すが再現しない

```
# echo "岡山県岡山市東区9999番地　デジタルビル　２号"|abrg -
[{"query":{"input":"岡山県岡山市東区9999番地　デジタルビル　２号"},"result":{"prefecture":"岡山県","match_level":2,"city":"岡山市東区","other":"9999番地 デジタルビル 2号","lat":null,"lon":null}}]
```

**Comment by koswatana** [comment]
入力が誤っている例だが
期待はotherに`1丁目3番地`と入るはずが、`丁目3番地`になってしまっている

```
'echo "東京都千代田区紀尾井町1丁目3番地"|abrg --format json -'|jq .
[
  {
    "query": {
      "input": "東京都千代田区紀尾井町1丁目3番地"
    },
    "result": {
      "prefecture": "東京都",
      "match_level": 3,
      "city": "千代田区",
      "town": "紀尾井町",
      "town_id": "0056000",
      "lg_code": "131016",
      "other": "丁目3",
      "lat": 35.681411,
      "lon": 139.73495
    }
  }
]
```

**Comment by koswatana** [comment]
このケースは意図どおりに動作しているのに
input: `東京都港区新橋１−０−０ デジタルビル１００`
other: `0-0 デジタルビル100`
output: `東京都港区新橋一丁目 0-0 デジタルビル100`

このケースはotherから`9-99`がなくなっています
input: `東京都港区新橋１－９－９９ デジタルビル９９９`
other: `デジタルビル９９９`
output: `東京都港区新橋一丁目 ラフィネス305`

期待するのは
input: `東京都港区新橋１－９－９９ デジタルビル９９９`
other: `9-99 デジタルビル999`
output: `東京都港区新橋一丁目  9-99 デジタルビル999`

- 実行例

```
% docker run --rm -v ${HOME}/ba000001:/root/.abr-geocoder abrg /bin/bash -c 'echo "東京都港区新橋１−０−０ デジタルビ ル１００"|abrg -'
[{"query":{"input":"東京都港区新橋１−０−０ デジタルビル１００"},"result":{"output":"東京都港区新橋一丁目 0-0 デジタルビル100","prefecture":"東京都","match_level":3,"city":"港区","town":"新橋一丁目","town_id":"0015001","lg_code":"131032","other":"0-0 デジタルビル100","lat":35.667928,"lon":139.758186}}]
% docker run --rm -v ${HOME}/ba000001:/root/.abr-geocoder abrg /bin/bash -c 'echo "東京都港区新橋１－９－９９ デジタ ルビル９９９"|abrg -'
[{"query":{"input":"東京都港区新橋１－９－９９ デジタルビル９９９"},"result":{"output":"東京都港区新橋一丁目 デジタルビル999","prefecture":"東京都","match_level":3,"city":"港区","town":"新橋一丁目","town_id":"0015001","lg_code":"131032","other":"デジタルビル999","lat":35.667928,"lon":139.758186}}]
```

**Comment by koswatana** [comment]
このケースは意図どおりに動作しているのに
input: `東京都港区新橋１−０−０ デジタルビル１００`
other: `0-0 デジタルビル100`
output: `東京都港区新橋一丁目 0-0 デジタルビル100`

このケースはotherから`9-99`がなくなっています
input: `東京都港区新橋１－９－９９ デジタルビル９９９`
other: `デジタルビル９９９`
output: `東京都港区新橋一丁目 デジタルビル999`

期待するのは
input: `東京都港区新橋１－９－９９ デジタルビル９９９`
other: `9-99 デジタルビル999`
output: `東京都港区新橋一丁目  9-99 デジタルビル999`

- 実行例

```
% docker run --rm -v ${HOME}/ba000001:/root/.abr-geocoder abrg /bin/bash -c 'echo "東京都港区新橋１−０−０ デジタルビ ル１００"|abrg -'
[{"query":{"input":"東京都港区新橋１−０−０ デジタルビル１００"},"result":{"output":"東京都港区新橋一丁目 0-0 デジタルビル100","prefecture":"東京都","match_level":3,"city":"港区","town":"新橋一丁目","town_id":"0015001","lg_code":"131032","other":"0-0 デジタルビル100","lat":35.667928,"lon":139.758186}}]
% docker run --rm -v ${HOME}/ba000001:/root/.abr-geocoder abrg /bin/bash -c 'echo "東京都港区新橋１－９－９９ デジタ ルビル９９９"|abrg -'
[{"query":{"input":"東京都港区新橋１－９－９９ デジタルビル９９９"},"result":{"output":"東京都港区新橋一丁目 デジタルビル999","prefecture":"東京都","match_level":3,"city":"港区","town":"新橋一丁目","town_id":"0015001","lg_code":"131032","other":"デジタルビル999","lat":35.667928,"lon":139.758186}}]
```

**Comment by maskatsum** [comment]
調査しますー

**Comment by gt-r-isobe** [comment]
町字マスターの小字がジオコーディング対象となっていないようです。ご確認をお願いいたします。

例）福島県いわき市山玉町脇川
アドレスBRとしてはレコードが存在しますが、ジオコーダーは大字までしかマッチングしません。

`[{"query":{"input":"福島県いわき市山玉町脇川"},"result":{"output":"福島県いわき市山玉町 脇川","prefecture":"福島県","match_level":3,"city":"いわき市","town":"山玉町","town_id":"0113000","lg_code":"072044","other":"脇川","lat":36.902887,"lon":140.695145}}]`

**Comment by maskatsum** [comment]
レポートを見る限りでは、異なる要因のものが、このissueに全て混ぜて投稿されているので、非常に管理しづらいです。そこで sub-issueを作って対応していきます

**Comment by zero3kw** [comment]
v1.0.0では正しく動作している
```
root@32cca304c335:/workspaces/abr-geocoder# abr-geocoder --version
1.0.0
root@32cca304c335:/workspaces/abr-geocoder# echo "東京都港区新橋１－９－９９ デジタルビル９９９"|abr-geocoder normalize -
┌──────────────────┬──────────┬───────────────┬──────────────────────┬──────────┬──────────┬────────────────────┬───────────┬────────────┐
│ マッチングレベル │ 都道府県 │ 市区町村      │ 町字                 │ 街区符号 │ 住居番号 │ 以降               │ 緯度      │ 経度       │
├──────────────────┼──────────┼───────────────┼──────────────────────┼──────────┼──────────┼────────────────────┼───────────┼────────────┤
│ 7                │ 東京都   │ 港区 (131032) │ 新橋一丁目 (0015001) │ 9 (009)  │          │ -99デジタルビル999 │ 35.667173 │ 139.760091 │
└──────────────────┴──────────┴───────────────┴──────────────────────┴──────────┴──────────┴────────────────────┴───────────┴────────────┘
```

- 小字に関してはv1.0.0でも対応できていない

```
root@32cca304c335:/workspaces/abr-geocoder# abr-geocoder --version
1.0.0
root@32cca304c335:/workspaces/abr-geocoder# echo "福島県いわき市山玉町脇川"|abr-geocoder normalize -
┌──────────────────┬──────────┬───────────────────┬──────────────────┬──────────┬──────────┬──────┬───────────┬────────────┐
│ マッチングレベル │ 都道府県 │ 市区町村          │ 町字             │ 街区符号 │ 住居番号 │ 以降 │ 緯度      │ 経度       │
├──────────────────┼──────────┼───────────────────┼──────────────────┼──────────┼──────────┼──────┼───────────┼────────────┤
│ 3                │ 福島県   │ いわき市 (072044) │ 山玉町 (0113000) │          │          │ 脇川 │ 36.902887 │ 140.695145 │
└──────────────────┴──────────┴───────────────────┴──────────────────┴──────────┴──────────┴──────┴───────────┴────────────┘
```

**Comment by maskatsum** [comment]
sub issues を全部対応したので、クローズ。必要なら新しい issue を提起してくださいー。
