### ISSUE TITLE
町字マッチングレベルの改良

### ISSUE THREAD

**Issue by koswatana** [digital-go-jp/abr-geocoder#71]
https://github.com/digital-go-jp/abr-geocoder/blob/main/README.ja.md?plain=1#L220

> 3	町字まで判別できた

を以下の2段階に分割する。

- 町字まで（町字コードすべて）判別できた
- 町字のうち大字・町まで（町字コード上4桁まで）判別できた

丁目や小字までの町字IDの全7桁が一致しなかったが、上4桁までは一致したことを返すことで、町字の一部までマッチングしたことを表現したいため。

ただし、条件として元々下3桁が000のレコードしかないケースは上4桁が一致＝「町字まで（町字コードすべて）判別できた」のマッチングレベルとするが、
下3桁が000以外のレコードがある場合には上4桁までは一致、全7桁では非マッチ、という判定を行う。

**Comment by koswatana** [comment]
アドレス・ベース・レジストリ データ解説書
<2022 年 4 月 試験公開版>
https://www.digital.go.jp/assets/contents/node/basic_page/field_ref_resources/3d996df3-f87c-4439-b474-c0fbbf3ddad8/d010b173/20220422_policies_base_registry_manual_01.pdf

![image](https://github.com/digital-go-jp/abr-geocoder/assets/103909883/e26f593d-bc89-4b0b-8821-b2b46aad7c0f)

**Comment by maskatsum** [comment]
# v2.0.0

```json
[
  {
    "query": {
      "input": "東京都千代田区霞が関4-1-2"
    },
    "result": {
      "output": "東京都千代田区霞が関4-1-2",
      "other": "4-1-2",
      "score": 1,
      "match_level": "machiaza",
      "coordinate_level": "city",
      "lat": 35.694003,
      "lon": 139.753634,
      "lg_code": "131016",
      "machiaza_id": "0002000",
      "rsdt_addr_flg": -1,
      "blk_id": null,
      "rsdt_id": null,
      "rsdt2_id": null,
      "prc_id": null,
      "pref": "東京都",
      "county": null,
      "city": "千代田区",
      "ward": null,
      "oaza_cho": "霞が関",
      "chome": null,
      "koaza": null,
      "blk_num": null,
      "rsdt_num": null,
      "rsdt_num2": null,
      "prc_num1": null,
      "prc_num2": null,
      "prc_num3": null
    },
    "debug": {
      "pref_key": 5859431,
      "city_key": 3666149537,
      "town_key": 1222974,
      "spendTime": "0.02"
    }
  }
]
```
