### ISSUE TITLE
丁目以降の数字（丁目・番地）の表記の揺れによって abrg コマンドの出力にばらつきがある

### ISSUE THREAD

**Issue by stayaDigi** [digital-go-jp/abr-geocoder#78]
■達成したいこと
丁目以降の数字（丁目・番地）の表記が揺れている2つの住所があり、`abrg` コマンドを使うことによって、同一の住所と判定したい（＝表記ゆれの正規化の目的で `abrg` を使いたい）ため、どのように実現可能かを検証したい。

■これまで実施した手順
- 比較したい「住所A」「住所A’」がある
- 「住所A」と「住所A'」は、表記ゆれがあるが、人間の目で見ると同一の住所と判別できる
  - （表記ゆれの例：漢数字 vs アラビア数字、アラビア数字の中でも全角数字 vs 半角数字、マンション名の有無）
- 「住所A」「住所A'」をともに `abrg` に入力し、出力結果を連結し、２つの文字列として比較。一致・不一致を確認

■実施例

例①
- 住所A：東京都港区南麻布５－１０－２７ー５１６
→（abrgコマンドからの出力を連結したもの）東京都港区南麻布五丁目
- 住所A’：東京都港区南麻布五丁目１０番２７
→（abrgコマンドからの出力を連結したもの）東京都港区南麻布五丁目

例②
- 住所B：広島県広島市安佐北区口田南４丁目２１番７号
→（abrgコマンドからの出力を連結したもの）広島県広島市安佐北区口田南四丁目217
- 住所B’：広島市安佐北区口田南四丁目２１番７号
→（abrgコマンドからの出力を連結したもの）広島県広島市安佐北区口田南四丁目21番7号

例③
- 住所C：東京都港区三田２－２－１８三田マンション３０４
→（abrgコマンドからの出力を連結したもの）東京都港区三田二丁目田マンション304
- 住所C'：東京都港区三田二丁目２番１８−３０４号
→（abrgコマンドからの出力を連結したもの）東京都港区三田二丁目号

※実際のコマンドの実行例は別途、以下に記載します

■所見
例①について
- 丁目については期待通りの挙動。「５」と「五丁目」がどちらも「五丁目」となっている
- 比較としては一致しているが、「丁目」以降（番地？）が `abrg` によって完全削除されてしまっており、期待していた結果と異なる

例②について
- 丁目については期待通りの挙動。「4丁目」と「四丁目」がどちらも「四丁目」となっている
- 番地以降については別住所になってしまっている（21番7号を217としてしまっている）期待していた結果と異なる

例③について
- 丁目については期待通りの挙動。「２」と「二丁目」がどちらも「二丁目」となっている
- `abrg` により「三田マンション」の「三」がつぶれてしまっている。「～丁目」以降の数字は場合によっては削除される？期待していた結果と異なる

■質問内容

- 上記の動作は `abrg` として想定の動作でしょうか、あるいはコマンドの実行方法が間違っていたり、実行の仕方次第で避けられるようなものでしょうか？
※コマンドの実行例の詳細は別途以下に記載します
- また、そもそも「■達成したいこと」を実現するうえで、別の良い方法がもしありましたら、ご教示頂ければと思います。

■関連と思われるIssue
https://github.com/digital-go-jp/abr-geocoder/issues/71

**Comment by stayaDigi** [comment]
以下にコマンドの実行結果を記載します。

例①
```% echo "東京都港区南麻布５－１０－２７ー５１６" | abrg - | jq
[
  {
    "query": {
      "input": "東京都港区南麻布５－１０－２７ー５１６"
    },
    "result": {
      "prefecture": "東京都",
      "match_level": 3,
      "city": "港区",
      "town": "南麻布五丁目",
      "town_id": "0021005",
      "lg_code": "131032",
      "other": "",
      "lat": 35.653403,
      "lon": 139.72453
    }
  }
]```
```% echo "東京都港区南麻布五丁目１０番２７" | abrg - | jq
[
  {
    "query": {
      "input": "東京都港区南麻布五丁目１０番２７"
    },
    "result": {
      "prefecture": "東京都",
      "match_level": 3,
      "city": "港区",
      "town": "南麻布五丁目",
      "town_id": "0021005",
      "lg_code": "131032",
      "other": "",
      "lat": 35.653403,
      "lon": 139.72453
    }
  }
]```

例②
```% echo "広島県広島市安佐北区口田南４丁目２１番７号" | abrg - | jq
[
  {
    "query": {
      "input": "広島県広島市安佐北区口田南４丁目２１番７号"
    },
    "result": {
      "prefecture": "広島県",
      "match_level": 8,
      "city": "広島市安佐北区",
      "town": "口田南四丁目",
      "town_id": "0042004",
      "lg_code": "341061",
      "other": "",
      "lat": 34.456818812,
      "lon": 132.500156749,
      "block": "21",
      "block_id": "021",
      "addr1": "7",
      "addr1_id": "007",
      "addr2": "",
      "addr2_id": ""
    }
  }
]```
```% echo "広島市安佐北区口田南四丁目２１番７号" | abrg - | jq
[
  {
    "query": {
      "input": "広島市安佐北区口田南四丁目２１番７号"
    },
    "result": {
      "prefecture": "広島県",
      "match_level": 2,
      "city": "広島市",
      "other": "安佐北区口田南四丁目21番7号",
      "lat": null,
      "lon": null
    }
  }
]```

例③
```% echo "東京都港区三田２－２－１８三田マンション３０４" | abrg - | jq
[
  {
    "query": {
      "input": "東京都港区三田２－２－１８三田マンション３０４"
    },
    "result": {
      "prefecture": "東京都",
      "match_level": 3,
      "city": "港区",
      "town": "三田二丁目",
      "town_id": "0019002",
      "lg_code": "131032",
      "other": "田マンション304",
      "lat": 35.64989,
      "lon": 139.741212
    }
  }
]```
```% echo "東京都港区三田二丁目２番１８−３０４号" | abrg - | jq
[
  {
    "query": {
      "input": "東京都港区三田二丁目２番１８−３０４号"
    },
    "result": {
      "prefecture": "東京都",
      "match_level": 3,
      "city": "港区",
      "town": "三田二丁目",
      "town_id": "0019002",
      "lg_code": "131032",
      "other": "号",
      "lat": 35.64989,
      "lon": 139.741212
    }
  }
]```

**Comment by koswatana** [comment]
@stayaDigi 

> 上記の動作は abrg として想定の動作でしょうか、あるいはコマンドの実行方法が間違っていたり、実行の仕方次第で避けられるようなものでしょうか？
https://github.com/digital-go-jp/abr-geocoder/issues/66
意図していない動作のため調査中です

> また、そもそも「■達成したいこと」を実現するうえで、別の良い方法がもしありましたら、ご教示頂ければと思います。

https://github.com/digital-go-jp/abr-geocoder/issues/42#issuecomment-1863189707
このように変更することを検討しているのですが、いかがでしょうか

**Comment by stayaDigi** [comment]
@koswatana 
ご返信ありがとうございます。

> https://github.com/digital-go-jp/abr-geocoder/issues/42#issuecomment-1863189707
> このように変更することを検討しているのですが、いかがでしょうか

はい、リンク先（#42）を拝見しましたが、この内容で問題ないと思います。

> v1.2.0でoutputに対応したが意図しない正規化とフィールド名が分かりづらいため修正を行う

とのことですが、この修正はいつ完了になるのか、目途等ありましたら教えて頂ければと思います。
※この名寄せ機能をGビズIDに組み込めるかどうかを判断したいための質問となります。お手数ですがよろしくお願いします。

**Comment by koswatana** [comment]
@stayaDigi 
ご確認いただきありがとうございます。
遅くても年度内には対応できるかと思います。

**Comment by stayaDigi** [comment]
@koswatana 
承知しました。ご回答ありがとうございます。

- 時期感的に、我々の開発に組み込むにはスケジュールははまらなさそうではあります。
- ですが、本修正が入りましたら、修正確認はしてみたいですので、その際はご連絡頂ければと思います。

**Comment by stayaDigi** [comment]
@koswatana 
本件ですが、`v.1.2.0` のリリースの結果、修正されたという認識で正しいでしょうか？
下記を見た結果、`v.1.2.0` はリリース済みであると判断しましたが、認識違いましたら教えて頂ければと思います。
https://github.com/digital-go-jp/abr-geocoder/tags
