### ISSUE TITLE
#66-1 出力結果に関する問題：”東京都千代田区紀尾井町1丁目3番地”

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#86]
# 概要

Geocodingの結果が正しく正規化されない

# 詳細

項目 | 値
-|-
入力値 | 東京都千代田区紀尾井町1丁目3番地
期待する出力値 |  東京都千代田区紀尾井町1丁目3
v1.2の出力値 |  東京都千代田区紀尾井町 丁目3

# 参照
https://github.com/digital-go-jp/abr-geocoder/issues/66#issuecomment-1849837965

**Comment by zero3kw** [comment]
```
# abr-geocoder --version
1.0.0
# echo "東京都千代田区紀尾井町1丁目3"|abr-geocoder normalize -
┌──────────────────┬──────────┬───────────────────┬────────────────────┬──────────┬──────────┬─────────┬───────────┬───────────┐
│ マッチングレベル │ 都道府県 │ 市区町村          │ 町字               │ 街区符号 │ 住居番号 │ 以降    │ 緯度      │ 経度      │
├──────────────────┼──────────┼───────────────────┼────────────────────┼──────────┼──────────┼─────────┼───────────┼───────────┤
│ 3                │ 東京都   │ 千代田区 (131016) │ 紀尾井町 (0056000) │          │          │ 一丁目3 │ 35.681411 │ 139.73495 │
```

**Comment by maskatsum** [comment]
`東京都千代田区紀尾井町1丁目3番地` の結果が、`マッチングレベル = 3`って、正しいんですかね。`other`ってのはジオコーディングできなかったということを意味します。

**Comment by maskatsum** [comment]
ああ、そうか。紀尾井町 は`丁目`の設定がないんですね ([wiki](https://ja.wikipedia.org/wiki/%E7%B4%80%E5%B0%BE%E4%BA%95%E7%94%BA)。

**Comment by maskatsum** [comment]
ああ、理解しました。紀尾井町は `「丁目」の設定のない単独町名`（[wiki](https://ja.wikipedia.org/w/index.php?title=%E7%B4%80%E5%B0%BE%E4%BA%95%E7%94%BA&oldid=98244542)）だから、 `東京都千代田区紀尾井町1番3号` が本来の住所表記。でも `東京都千代田区紀尾井町1丁目3番地` と間違えて表記されていることも多い。
よって、`東京都千代田区紀尾井町1丁目3番地` の場合は、正しくない住所のため、`マッチングレベル = 3` で良い。

**Comment by maskatsum** [comment]
Fixed
