### ISSUE TITLE
`nd` について

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#9]
https://github.com/maskatsum/abr-geocoder/blob/30ba379b0a44748c454938e0317220093cb10a0d/README.ja.md?plain=1#LL64C1-L65C1

日本語の説明を読んでも、最初、全く理解が出来ませんでした。ソースコードを読んで、初めて理解できました。
このような使い方はあまり一般的ではないと思うので、なにか別なフラグオプションを用意する方が良いと思います。
例えば、`--stream` のようなフラグオプションはいかがでしょうか。

example:

```
$ abr-geocoder normalize --stream <inputFile> 
```

**Comment by maskatsum** [comment]
* 個別会話より、記録のため、転載

> > nd を付けないとバッファする仕様は、なんででしょうか。
> 
> geojsonはfuturesで複数futureを返す、jsonは配列で要素を返すからかなと
> tableはストリーミングで出力してしまっても良い気がします

バッファリングするとメモリを圧迫するので、プログラムとしてはあまり健全ではないです。
また処理の途中で、で何かの理由でプログラムが終了してしまうと、それまでの結果を得ることが出来ないまま、終了となってしまいます。
（例えば 100,000個の住所があり、最後の1個の住所にエラーがあり、プログラムが終了してしまうなどと、99,999個の正常な結果が出力されない。）

なので不正確なフォーマットでも出力するほうが望ましいです。
(REST APIを作るなら話は別です）

---------

改善するアイディアはありますが、まだコードを読んでいないので、とりあえずpending。将来的にバッファリングすることを廃止しましょう

**Comment by koswatana** [comment]
本ツールを元にREST APIの開発を検討中です

**Comment by maskatsum** [comment]
v1.1 にて解決しました。v1.1 では全体をストリーム処理するようにしてあり、出力も最後まで溜め込まずに、すぐにアウトプットしてしまいます。`json`でも`ndjson`でも溜め込みません。`json`の場合のみ、最後にjsonの形になるように調整をしています。

**Comment by maskatsum** [comment]
`ndjson` とは、`Newline Delimited JSON`
https://github.com/ndjson/ndjson-spec
