### ISSUE TITLE
調査：TypeORM への対応

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#97]
[TypeORM](https://typeorm.io/) への変更を検討してみる。

**Comment by koswatana** [comment]
better-sqlite3が原因のIssue
- https://github.com/digital-go-jp/abr-geocoder/issues/40
- https://github.com/digital-go-jp/abr-geocoder/issues/85

**Comment by sanak** [comment]
TypeORMへの対応ですが、以前試したものを以下のPRで整理していますので、よろしければご参考ください。
* [TypeORMサポートのトライアル by sanak · Pull Request #1 · sanak/abr-geocoder](https://github.com/sanak/abr-geocoder/pull/1)

**Comment by maskatsum** [comment]
@sanak さん、ありがとうございます！検証してみます！

**Comment by sanak** [comment]
@maskatsum 確認頂き、ありがとうございます。
該当PRの説明欄を適宜更新していくようにしますので、よろしくお願いいたします。🙇

**Comment by maskatsum** [comment]
開発中のv2 で、複数のDBタイプを導入できるように構造上は設計しました。なので将来的には、外部DBもサポートしていきます。
でもしばらくは SQLite のままで実装していきたいと思います。

**Comment by maskatsum** [comment]
@sanak さん

v1 の際にはお世話になりました。

本日、v2.0.0 をリリースしました。
結果的に SQLのチューニングを必要としたため、TypeORM は採用しませんでした。
ただ、抽象化レイヤーは実装したので、MySQL / Postgres 等には対応していきたいと思います。

**Comment by sanak** [comment]
@maskatsum さん
上記、了解いたしました。
ご連絡頂き、ありがとうございます！🙇‍♂️
